- lib/discovery/index.js
- lib/types.js
- types/modules.d.ts
Towards #14 
wow i thought this would be easier...
Notes:
- A few todo comments but will point them out and see if they're blocking (most aren't)
> chore: add types for @hyperswarm/secret-stream

- types/modules.d.ts
Towards #14 
Notes:
- This also adds the definitions for [`random-access-storage`](https://github.com/random-access-storage/random-access-storage/) since `random-access-memory` extends it
> chore: add types for random-access-memory

- tests/discovery.js
Closes #18. May add more to this but can iterate later on too.
Adds tests for:
- Replication over mDNS
- Ensuring that connections are made over valid discovery mechanism
> chore: add more tests for discovery

- types/modules.d.ts
Towards #14 
I misunderstood how `readonly` works and and had to review my usage of it and update accordingly. Also makes some minor type fixes and improvements
> chore: fix types for some modules

- types/modules.d.ts
Towards #14. Follow up for https://github.com/digidem/mapeo-core-next/pull/41#discussion_r997452665
Was thinking about defining the `RelayAddress` interface in `dht-rpc` but that seemed to low-level. Placing it in `@hyperswarm/dht` feels appropriate to me
> chore: add type annotation for relay address

- types/modules.d.ts
Towards #14 
Think it makes sense to keep types scoped to the relevant module where possible. may turn out to be an unwise decision later on 😄
> chore: clean up types implementation for dht-rpc

- types/modules.d.ts
Seems like we're using `crypto.randomBytes`, which should be derived from the `@types/node`, so figured it should be okay to remove the module declaration here
> chore: remove randombytes ts module declaration

- types/modules.d.ts
Towards #14 
- Only adds definitions for the Node implementation, not the browser one, which seems out of scope (interested to have them but don't know how to create the separation properly in a declaration file, if possible)
> chore: add types for b4a

- types/modules.d.ts
Towards #14 
because I didn't know how to properly type classes that extend EventEmitters 🤦‍♂️
> chore: use tiny-typed-emitter for module types that extend EventEmitter

- lib/core-manager/core-index.js
- lib/core-manager/index.js
- lib/core-manager/messages.d.ts
- lib/core-manager/messages.js
- lib/core-manager/replication-state-machine.js
- package-lock.json
- package.json
- proto/buf.gen.yaml
- proto/buf.yaml
- proto/messages.proto
- scripts/build-messages.js
- tests/core-manager.js
- tests/helpers/core-manager.js
- tsconfig.json
- types/corestore.d.ts
- types/hypercore-crypto.d.ts
- types/hypercore.d.ts
- types/modules.d.ts
These are some ideas, ~~WIP~~, for a "CoreManager" class for Mapeo.
It eagerly loads all the hypercores in the project, including writer cores for each namespace.
I am imagining that each module might use the `getCores(namespace)` method to get the cores to add to the indexer, and would also listen to the `add-core` event. And each module would also use the `getWriter(namespace)` method.
A thought about the extensions to share keys: what if we don't use extensions at all, and use the data in authStore for all keys? This would require the public key of the auth store from the peer being invited, and for us to write it as part of the record that adds that peer to the project.
That way auth store would be solely responsible for calling the `addCore` method as needed, but auth store would …
> feat: core-manager

- lib/core-manager/core-index.js
- lib/core-manager/index.js
- tests/core-manager.js
Persist cores that are added to the core manager. Fixes #86 
Todo:
> fix: persist cores

- lib/rpc/index.js
- lib/rpc/messages.d.ts
- lib/rpc/messages.js
- proto/rpc.proto
- tests/rpc.js
Adds support for sending multiple encryption keys (one for each namespace) along with an invite, and also adds support for an optional "projectConfig" buffer.
Actual handling of the projectConfig in the invite will need to be done in a follow up PR.
> feat: add projectConfig & encryptionKeys to invite

- lib/core-manager/core-index.js
- lib/core-manager/index.js
- tests/core-manager.js
- tests/helpers/core-manager.js
- types/corestore.d.ts
- types/hypercore.d.ts
Add support for block-level encryption of all hypercores. Separate encryption key for each namespace, to allow for future features (e.g. only sharing encryption key for specific namespaces). 
TODO after PR is merged:
> feat: support block encryption

- src/schema/client.js
- tests/schema.js
> feat: add schema definition for project keys table

- drizzle/client/0000_lonely_yellow_claw.sql
- drizzle/client/0000_unknown_umar.sql
- drizzle/client/meta/0000_snapshot.json
- drizzle/client/meta/_journal.json
- src/schema/client.js
Fixes a bug introduced in #169, as I used a `for...in` instead of a `for...of` loop...
Also creates the drizzle files becaues I forgot to do that in the other PR. My understanding is that it should be okay to overwrite the original migration files, as opposed to creating a new migration
Referencing #165 for linking purposes
> fix: properly generate column names in projectKeys table

- drizzle/project/0000_special_masque.sql
- drizzle/project/meta/0000_snapshot.json
- drizzle/project/meta/_journal.json
- package-lock.json
- package.json
- src/core-manager/index.js
- src/datastore/index.js
- src/datatype/index.d.ts
- src/datatype/index.js
- src/mapeo-project.js
- src/schema/schema-to-drizzle.js
- src/types.ts
- src/utils.js
- test-e2e/project-crud.js
- test-types/data-types.ts
- tests/schema.js
- types/brittle.d.ts
~~Currently depends on https://github.com/digidem/mapeo-schema/pull/117 and a new version of @mapeo/schema being published.~~
This adds two new data types: preset and field. They are stored in a new namespace called "config". The reason for keeping these data types in a separate namespace is to allow sync of only the config prior to syncing the rest of the data. We're not using the auth namespace because Mapeo Cloud needs the encryption key for that namespace, and we want to minimise the data that a server can see as unencrypted.
> feat: Add config store and preset & field types

- src/datatype/index.d.ts
- src/datatype/index.js
- tests/data-type.js
Fixes Add `dataType.createWithDocId()` method #190
TODO:
~~The type signature for [kCreateWithDocId]() is not quite right, but otherwise good to go.~~
Fixed the type issues, all ready for review & merge :)
> feat: Add internal `dataType.createWithDocId()`

- proto/rpc.proto
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- src/rpc/index.js
- tests/rpc.js
- add `config` namespace to encryptionKeys
- remove support for sending projectConfig
(now synced in db, not sent in invite)
- add projectInfo to invite - currently `name`
- make auth encryption key mandatory
> feat: update protobuf for RPC [2/3]

- drizzle/project/0000_volatile_jackal.sql
- drizzle/project/meta/0000_snapshot.json
- drizzle/project/meta/_journal.json
- src/capabilities.js
- src/core-ownership.js
- src/datastore/index.js
- src/mapeo-project.js
- src/schema/project.js
- test-e2e/capabilities.js
Implements #189
More complete tests are blocked by the ability to invite and sync devices, tracking that in #238 
This PR adds an internal `this.#capabilities` instance to the MapeoProject instance. It's initial use will be for assigning roles (part of the invite process) and for checking capabilities for sync when syncing with other devices. Checking capabilities for reading/writing mapeo docs is post-MVP. Also need to expose in the API, tracking that in #239
Post-MVP we will implement the ability have custom roles and capabilities, but hard-coding is ok for now.
> feat: add capabilities

- src/member-api.js
- tests/helpers/rpc.js
- tests/member-api.js
- tests/rpc.js
Towards #225 
- Introduces the `MemberApi` class
- Implements the `invite` method
TODO:
> initial implementation of invite method for MemberApi

- drizzle/client/0000_needy_hex.sql
- drizzle/client/meta/0000_snapshot.json
- drizzle/client/meta/_journal.json
- package-lock.json
- package.json
- src/mapeo-manager.js
- src/mapeo-project.js
- src/schema/client.js
- src/types.ts
- src/utils.js
Closes #234 
Notes:
- Updates `@mapeo/crypto` to 1.0.0-alpha.8
- Adds two opaque types: `ProjectId` and `ProjectPublicId`.
- `ProjectId` refers to the "internal" project id, whereas `ProjectPublicId` is what's used for client consumption
- Adds a `projectPublicId` column to the `projectKeys` client db table
- Tried a couple of things, but wasn't able to get Drizzle to understand that the `projectPublicId` column should store and return the opaque `ProjectPublicId` type. Pretty sure there's a way but my initial attempts failed me. For now, there are a couple of type casts in the manager code.
> update MapeoManager to return and handle project public IDs

- proto/buf.gen.yaml
- proto/extensions.proto
- src/core-manager/index.js
- src/generated/extensions.d.ts
- src/generated/extensions.js
- src/generated/extensions.ts
- src/generated/keys.d.ts
- src/generated/keys.js
- src/generated/keys.ts
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- tests/blob-server.js
- tests/blob-store/blob-store.js
- tests/core-manager.js
- tests/helpers/blob-store.js
Fixes #251
This adds new fields to the project extension to share keys for other
namespaces and updates tests which manually added cores (manual adding
is no longer needed, but do need to wait for cores to be added)
> feat: share all core keys via extension messages

- src/member-api.js
- tests/member-api.js
Closes #257 
Currently stacked on #262 
Lacking some tests as I intend to write more e2e once more methods are implemented
> feat: add getMany method to member api

- src/ipc-wrapper/client.js
- src/ipc-wrapper/server.js
- src/mapeo-manager.js
- src/types.ts
- src/utils.js
- test-e2e/ipc-wrapper.js
Towards #278
I had introduced opaque types for project id and project public id, but made the mistake of using those for the public-facing API, which makes their usage more tedious and doesn't bring any major benefit for now. 
Opaque types are useful if usage is kept internally, but maybe that's something to revisit later on.
Doing this towards publishing the IPC wrapper as a separate module, which works with APIs that used to rely on these opaque types.
> chore: remove usage of opaque ids types related to project ids

- package.json
- src/mapeo-manager.js
- src/mapeo-project.js
- tests/data-type.js
Towards #278 
Attempting to use `@mapeo/core` as a dep in a separate project breaks because:
1. We don't include the drizzle migration directories when publishing
2. The path string we provide to drizzle's `migrate()` function is not absolute, which breaks when this is being used as dependency (implementation of how Drizzle attempts to find the migration files based on the provided path is [here](https://github.com/drizzle-team/drizzle-orm/blob/a7dc7e8bbdc3784f67ff32ce39bee3283f080751/drizzle-orm/src/migrator.ts#L22))
I encountered these by using `npm pack` on this repo and then importing as a dep in separate project
> fix: fix usage of drizzle when core is used as a dep

- src/core-manager/index.js
- src/core-manager/replication-state-machine.js
- tests/core-manager.js
This enables the sync API for disabling sync by adding an "unreplicate"
function that removes a core from the replication stream, without
closing the stream. Unreplicating a core from a replication with a peer
is currently the only way to stop a peer from receiving data from you -
Hypercore has no API yet for blocking uploads to peers when they request
data.
TODO:
> feat: disable namespace replication

- src/mapeo-manager.js
- test-e2e/manager-invite.js
- tests/helpers/rpc.js
Closes #212 
There are some commented-out test assertions that would be nice to have but I _think_ we're missing some pieces related to sync in order to do that. Could be mistaken though...
> feat: add invite namespace to MapeoManager

- src/index.js
- test-types/data-types.ts
Towards #278 
Waiting for #283 to be merged since it also includes some relevant changes
Summary of changes (so far):
> feat: update main exports

- src/mapeo-manager.js
- src/mapeo-project.js
- src/member-api.js
- src/utils.js
- test-e2e/capabilities.js
- tests/member-api.js
Closes #239 
Exposes capabilities in the following ways:
- adds a `$getOwnCapabilities()` method to `MapeoProject`
- adds a `capabilities` field to the return value of `project.$member.getById()` and `project.$member.getMany()`
TODO:
- the e2e capabilities tests should ideally be able to use `project.$member` to retrieve the capabilities. currently relies on https://github.com/digidem/mapeo-core-next/issues/289 and updating the `MemberApi.invite()` implementation
- the e2e manager invite tests should check that the inviter can retrieve the member's device info using the member api after the invite is accepted
> feat: expose capabilities in MapeoProject and its member api

- drizzle/client/0000_foamy_madame_hydra.sql
- drizzle/client/meta/0000_snapshot.json
- drizzle/client/meta/_journal.json
- drizzle/project/0000_brown_living_mummy.sql
- drizzle/project/meta/0000_snapshot.json
- drizzle/project/meta/_journal.json
- package-lock.json
- package.json
- src/blob-store/index.js
- src/core-manager/index.js
- src/core-ownership.js
- src/datastore/index.js
- src/datatype/index.js
- src/index-writer/index.js
- src/mapeo-project.js
- src/types.ts
- src/utils.js
- test-e2e/core-ownership.js
- tests/blob-api.js
- tests/blob-server.js
- tests/blob-store/blob-store.js
- tests/core-ownership.js
- tests/datastore.js
Closes #265 
Closes #272
Extracts the relevant changes from #271 
This version of `@mapeo/schema` introduced the following:
- this one doesn't have many direct changes from schema, but requires us to derive the drive ids differently
> chore: update @mapeo/schema to 3.0.0-next.10

- src/core-manager/index.js
- tests/core-manager.js
Fixes #309, removes responsibility from CoreManager to track peer-have
messages - will be handled by SyncState class
> chore: emit peer-have messages, don't persist them

- src/datatype/index.js
- test-types/data-types.ts
Closes #301
Decided to go with throwing an error if not found since 
1. all of the existing code that uses this method is written based on that type definition. 
2. it aligns more closely with the [client docs](https://github.com/digidem/mapeo-core-docs/blob/4359febd84163c28cc0ae55d6bbf08f150d592e3/client-docs/README.md#mapeodocgetbydocid) i had spec'd a while ago
Not a huge fan of it, as explained in https://github.com/digidem/mapeo-core-next/issues/301#issuecomment-1747452577, but this approach requires the smallest amount of changes and is fine for now
> fix: fix DataType.getByDocId implementation to match type definition

- proto/buf.gen.yaml
- proto/extensions.proto
- src/core-manager/index.js
- src/generated/extensions.d.ts
- src/generated/extensions.js
- src/generated/extensions.ts
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- tests/core-manager.js
> feat: add namespace to peer pre-have messages

- .husky/post-checkout
- .husky/post-merge
- .husky/pre-commit
- package-lock.json
- package.json
Non-urgent, but I've been meaning to add this for a while so that files are always formatted with prettier. This also adds a warning when you do `git pull` or `git checkout` if package-lock.json is different and whether `npm install` needs to be run
> chore: commit hooks for lint & package-lock chk

- src/discovery/mdns.js
- tests/discovery/mdns.js
The dedupe logic was incorrect, but in most cases the check in
`handleServiceUp` was hiding that. Temporarily removing that check
revealed the bug in a reproducible way.
> fix: fix mdns discovery (finally)

- .github/workflows/node.yml
Updates to actions/checkout@v4 and actions/setup-node@v2
Removes deprecation warnings
> chore: update github action steps

- .gitignore
started appearing after husky lint on commit hook (which uses the cache)
> chore: gitignore .eslintcache

- src/capabilities.js
- test-e2e/capabilities.js
Returns capabilities for all devices in a project - this is the source
of truth of who is in the project
> feat: add capabilities.getAll()

- .github/workflows/node.yml
Currently CI only runs for PRs against `main`, which means it does not
run for stacked PRs. This changes the CI workflow to run on all PRs
> chore: run CI on PRs against any branch

- src/datastore/index.js
- tests/datastore.js
> Feat: add DataStore.writeRaw method

- package-lock.json
- package.json
Upgrades `better-sqlite3` from `8.5.0` to `8.7.0`. Doing this because I'm planning to build the prebuilds for 8.7.0, so I wanted them to match initially
[v9](https://github.com/WiseLibs/better-sqlite3/releases/tag/v9.0.0) was recently released but refraining due to dropped official support for Node 16
> chore: update better-sqlite3 to 8.7.0

- package-lock.json
- package.json
Updates `type-fest` from 3.10.0 to 4.5.0 and moves it to a normal dependency. The latter is necessary for type definitions to work as expected when `@mapeo/core` is used as a dependency in other projects.
> chore: update type-fest and move to normal deps

- src/invite-api.js
- src/rpc/index.js
- tests/helpers/rpc.js
- tests/invite-api.js
- tests/rpc.js
Trying to send an RPC message immediately after connecting the RPC
channel would fail because the protomux channel was not yet open. This
fix ensures that sending an RPC message waits for a peer to fully
connect before trying to send. This is necessary for sending device info
(e.g. the device name) immediately after connecting to a peer.
> fix: Fix sending RPC messages after connection

- src/local-peers.js
- src/mapeo-manager.js
- src/mapeo-project.js
- src/sync/sync-controller.js
- test-types/data-types.ts
Stacked on #356
This is a lot of plumbing to connect everything together.
- Replication with local peers now happens at the MapeoManager level, and multiple projects can sync over the same connection (this is done via `protomux.pair()` on the hypercore protocol identifier, which gets us an event with the discovery key whenever a hypercore is replicated, and we pass this discovery key to the project instance via the LocalPeers class.
- Adds a `mapeoManager.replicate()` method, for replicating directly with a stream rather that just using discovery (may move this to a symbol method - would mainly be for testing)
- Narrows types for replication methods to be clearer about what should be passed where. This is a bit confusing, mainly due to the complex actual types used by Hypercore.
- A local …
> feat: integrate LocalDiscovery & LocalPeers

- src/blob-api.js
- tests/blob-api.js
Closes #368 
Honestly a super naïve attempt but hoping it does the main thing.
> fix: fix writing to blob store when also calculating content hash

- src/local-peers.js
- tests/local-peers.js
> fix: handle duplicate connections to LocalPeers

- .github/workflows/release.yml
Fixes #359 
Noticed an error about missing a `build` npm script: https://github.com/digidem/mapeo-core-next/actions/runs/6882793274/job/18722037582#step:3:164
> npm ERR! Missing script: "build"
Not entirely sure what the necessary change is, but figured at least removing the step that fails would be a good start.
> chore: fix release workflow configuration

- package-lock.json
- package.json
Tomas was dealing with issues because of a mangled lockfile, which updated a transitive dep (hyperblobs) and caused issues in our tests.
This change won't fix that scenario, but just to avoid other potential headaches in the future, pinning any hyper deps that haven't been pinned yet.
> chore: pin more hyper deps

- src/mapeo-manager.js
- src/mapeo-project.js
- test-e2e/capabilities.js
- test-e2e/core-ownership.js
- test-e2e/device-info.js
- test-e2e/manager-basic.js
- test-e2e/manager-invite.js
- test-e2e/media-server.js
- test-e2e/members.js
- test-e2e/project-crud.js
- test-e2e/project-settings.js
- test-types/data-types.ts
Should close #341 
For now:
* add optional opt for projectMigrationFolder to mapeoProject with default value
* add optional opt for projectMigrationFolder and clientMigrationFolder to mapeoManager with default values
Since I put a default value to both params I made both of them optionals, but maybe it not the right approach?
Also the types for both are strings and then turned into a path with `new URL`
> feat: dbMigrationPathOpt - add db migration path to `MapeoProject` and `MapeoManager`

- types/brittle.d.ts
stacked on #383 to fix some additional type issues, mainly that the default export and `test.solo()` were not typed correctly, plus some fixes for incorrect docs (types reflect actual source code)
> fix: fix brittle types

- types/brittle.d.ts
Noticed issues with the definitions for `t.exception` and all of the ones that are coercible
> chore: fix Brittle type definitions

- src/core-ownership.js
- src/datatype/index.d.ts
- src/datatype/index.js
- src/mapeo-manager.js
- src/mapeo-project.js
- test-e2e/capabilities.js
- test-e2e/core-ownership.js
- test-e2e/device-info.js
- test-e2e/media-server.js
- test-e2e/members.js
Stacked on #362
This PR lays some groundwork for #228, removing the `project.ready()` method and the need to await it. Writing the coreownership owner record is moved inside the core ownership function, and reading core ownership data will wait for the core ownership record to be written before reading data.
> feat: remove project.ready()

- src/mapeo-manager.js
- test-e2e/manager-basic.js
- test-e2e/media-server.js
Closes https://github.com/digidem/mapeo-core-next/issues/391
Renames them to `startMediaServer()` and `stopMediaServer()`, respectively
> rename MapeoManager.start() and MapeoManager.stop() methods

- src/capabilities.js
Not sure how TS was still able to infer the roleId param type correctly prior to this with the incorrect declaration, but not worth musing over 😄
> chore: fix param type for Capabilities.assignRole()

- docs/guides/media-server.md
Closes #398 
Not exhaustive but hopefully enough to be useful actual usage in an app context.
Wasn't sure about where to put this but this directory seemed to be suitable for now.
> add docs for using the media server and relevant APIs

- src/mapeo-manager.js
- src/sync/peer-sync-controller.js
- src/sync/sync-api.js
- test-e2e/sync.js
- test-e2e/utils.js
Previously the public sync state separated sync state by namespace and
by peer. This information is not currently used by the UI, so this PR
omits peer states and sums the namespace sync states into 'initial' and
'data'.
This also adds a `syncing` property to the `initial` and `data` sync states, that is true if that subset of the database is currently enabled for sync.
This also adds a `connectedPeers` property that is the number of connected peers.
> feat: reduce & simplify sync state

- src/datatype/index.js
- tests/data-type.js
The internal `dataType[kCreateWithDocId]()` method should not allow you to create two documents with the same `docId`. This creates a "fork", which can lead to unexpected behaviour. The existing doc should be updated instead with `dataType.update()`.
This PR checks if there is an existing document with the given docId and throws if it exists.
> feat: throw an Error when creating with an existing docId

- src/datatype/index.d.ts
- src/datatype/index.js
- test-e2e/project-crud.js
- test-types/data-types.ts
- tests/data-type.js
Fixes "`dataType.delete()` should use `docId` not `versionId`" (#422)
The deletion document links to all forks, if forks exist.
> fix!: delete() by docId not versionId(s)

- src/core-manager/index.js
- tests/core-manager.js
Towards #241 . Extracted from #410 
Implements a `CoreManager.deleteData()` method for deleting data from cores for a given namespace. By default, it will not delete data that resides in its writer core but that can be changed using the `deleteOwn` opt.
> feat: add method for deleting core data from storage

- tests/tsconfig.json
- tsconfig.json
Closes #416 
This doesn't include any npm script updates or a step to typecheck the tests. Mostly useful as we're writing tests for editor feedback for now.
Didn't feel inclined to include fixes to the type issues that were found as a result of this PR. Happy to try since I believe most are probably straightforward to address. 
Current state of checks as of now:
```sh
Found 173 errors in 16 files.
Errors  Files
14  tests/bitfield-rle.js:7
4  tests/blob-store/blob-store.js:416
5  tests/blob-store/combine-states.js:40
12  tests/blob-store/live-download.js:19
53  tests/core-manager.js:25
1  tests/core-ownership.js:79
4  tests/data-type.js:123
4  tests/datastore.js:29
23  tests/discovery/dns-sd.js:19
8  tests/discovery/local-discovery.js:69
4  tests/fastify-plugins/blobs.js:295
7 …
```
> chore: add tsconfig for tests/ directory

- .prettierignore
This adds a [.prettierignore](https://prettier.io/docs/en/ignore.html#ignoring-files-prettierignore) to prevent formatting of generated files.
Fixes #216.
> chore: don't run Prettier on generated files

- src/mapeo-manager.js
- test-e2e/project-leave.js
I _think_ this is needed in order to avoid some bugs related to using a stale project reference. Also have a todo to write an e2e test for leaving and then rejoining, since my early attempt has not been successful 🤔 (which may highlight other issues?)
> fix: remove stale project reference in manager when leaving a project

- package-lock.json
- package.json
- types/modules.d.ts
Types for nanobench were [recently added to DefinitelyTyped][0], so we can use them.
The `benchmarks` directory is not currently type-checked, so this change has no impact, but it should make it easier to type-check in the future.
[0]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68221
> chore: add types for nanobench

- src/discovery/dns-sd.js
This replaces our custom `isIpv4` function with [`net.isIPv4`][0], which is built into Node.
`net.isIPv4` is stricter than ours (see [Node's source][1]), but it's the same basic thing.
[0]: https://nodejs.org/api/net.html#netisipv4input
[1]: https://github.com/nodejs/node/blob/f820efe0851dd3c64d673156b037ce7e8648fd81/lib/internal/net.js#L31-L36
> chore: prefer `net.isIPv4` over custom function

- src/discovery/dns-sd.js
This is slightly clearer and slightly more efficient.
> chore: prefer `.find(fn)` over `.filter(fn)[0]`

- src/mapeo-manager.js
- test-e2e/device-info.js
> feat: return `deviceId` from `getDeviceInfo()`

- src/core-manager/index.js
- src/mapeo-project.js
- tests/core-manager.js
When you leave a project, we no longer delete your own data (but still
close your writer Hypercore).
Because this was the last occurrence of `deleteOwn: false`, I removed
the option entirely.
Fixes #449.
> chore: don't delete own data when leaving a project

- types/brittle.d.ts
`t.teardown` [doesn't care about the return type of its callback][0] so I updated the types to match.
[0]: https://github.com/holepunchto/brittle/blob/8926893862dc1ecf9a213fedf2306f24fe47b8cc/index.js#L640
> chore: use looser type for Brittle's teardown function

- package-lock.json
- package.json
- types/modules.d.ts
[@types/sub-encoder was recently created][0] so we can use that instead of defining our own type.
[0]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68390
> chore: use upstream types for sub-encoder

- test-e2e/project-leave.js
`t.ok(myPromise)` should probably be `t.ok(await myPromise)`.
I noticed a spot where we weren't doing this so I thought I'd fix it.
In the long term, we may wish to add an ESLint rule to avoid floating promises...but I think this is useful in the short term.
> test: assert on result, not promise itself

- tests/mapeo.js
This test has been around for over a year unused, so we can remove it.
> chore: remove useless test

- test-e2e/local-peers.js
This minor test-only change improves the types for a helper function.
> chore: remove `any` type in local peers test

- src/local-peers.js
This change, which should have no user impact, improves the type for a local peer callback. This is one of the last remaining changes required to enable the [strictFunctionTypes] TypeScript compiler option.
[strictFunctionTypes]: https://www.typescriptlang.org/tsconfig/#strictFunctionTypes
> chore: use stricter function type for callback

- src/local-peers.js
- tsconfig.json
This enables the [noImplicitThis] TypeScript option for improved type safety.
We had one small violation which I fixed here.
[noImplicitThis]: https://www.typescriptlang.org/tsconfig/#noImplicitThis
> chore: enable noImplicitThis TypeScript option

- src/blob-store/index.js
- src/core-manager/index.js
- tsconfig.json
_I recommend [reviewing this with whitespace changes disabled](https://github.com/digidem/mapeo-core-next/pull/492/files?w=1)._
This enables the [strictPropertyInitialization] TypeScript compiler option for improved type safety.
There were two places where we were violating this rule...no longer!
[strictPropertyInitialization]: https://www.typescriptlang.org/tsconfig/#strictPropertyInitialization
> chore: enable strictPropertyInitialization TypeScript option

- src/local-peers.js
This change should have no impact.
I think this variable was meant to be called "last emitted peers", not "last emitter peers". This renames the variable.
> chore: correct property name

- src/sync/sync-api.js
This is a minor change.
`SyncApi.prototype.waitForSync` could return `Promise<void>` or `Promise<null>`.
This makes the function return a consistent value, `Promise<void>`.
> chore: use consistent resolution value in sync method

- test-e2e/utils.js
This method returns synchronously, so we don't need to await it.
`git grep -w getState | grep -w await` returns no results after this change, so I think this is the only spot where we do this.
> chore: remove unnecessary await from test utility

- .github/workflows/node.yml
This removes Node 16 support, given that (1) it is deprecated (2) it [is no longer used in CoMapeo][0].
[0]: https://github.com/digidem/CoMapeo-mobile/pull/194
> chore!: drop Node 16 support

- src/config-import.js
- src/utils.js
- tests/config-import.js
I had a problem where the config import tests failed. This seemed to be because the `JSON.parse()` error message can change.
For example, `JSON.parse('{bad')` gives the following error message in Firefox v123:
expected property name or '}' at line 1 column 2 of the JSON data
But Node v20 gives the following:
Expected property name or '}' in JSON at position 1
We now catch this error and return a consistent message, which should make the tests more reliable. Because this code was getting a little long, I moved it into its own function.
> chore: update config import error

- src/mapeo-manager.js
- test-e2e/device-info.js
- test-e2e/local-peers.js
- test-e2e/members.js
_I recommend [reviewing this with whitespace changes disabled](https://github.com/digidem/mapeo-core-next/pull/508/files?w=1)._
Closes #502.
> feat: send device info changes to connected peers

- src/mapeo-project.js
- src/member-api.js
- src/roles.js
_This change should have no user impact, and is not urgent._
I generally prefer `Map`s to `Record`s when the keys are variable. This is mainly due to bugs with keys like `hasOwnProperty` or `__proto__`, but they also allow non-string keys.
As far as I could tell, we were always using `Map`s in relevant spots except for `Roles.prototype.getAll()`...but no longer!
> chore: use `Map`, not `Record`, for listing all roles

- package-lock.json
- package.json
- src/fastify-plugins/maps/index.js
- src/fastify-plugins/maps/offline-fallback-map.js
- src/fastify-plugins/maps/static-maps.js
- src/fastify-plugins/utils.js
- src/index.js
- tests/fastify-plugins/maps.js
- tests/fastify-plugins/offline-fallback-map.js
- types/fastify.d.ts
Towards #439 
Stacked on #435 
Implements a fastify plugin for serving a fallback map in the case of not having an available local "default" static map or being offline. The plugin accepts required options for specifying where the style definition lives and the directory containing the geojson sources (this provides flexibility for consumers that may not necessarily be using something like `mapeo-offline-map`, or happen to change the filesystem structure).
TODO:
> feat: add functionality to serve offline fallback map

- package-lock.json
- package.json
- src/fastify-plugins/maps/index.js
- test-e2e/manager-fastify-server.js
- tests/fastify-plugins/maps.js
- tests/fixtures/map-style-definitions/mapbox-outdoors-v12.json
- tests/fixtures/map-style-definitions/protomaps-dark-v2.json
Closes #439 
Closes #448
Stacked on #450 
Notes:
- implements the online proxying component of determining which style.json to return handling the stable style url endpoint. Currently assumes that the client will provide an `key` query param when requesting the stable style json endpoint (as opposed to us using some hardcoded token)
- e2e test(s) will be implemented once #457 is merged
TODO:
- ~Do we want to incorporate a compression plugin? (e.g. https://github.com/fastify/fastify-compress/). Most of the time, these upstream providers are compressing the responses but since we don't have anything set up, our forwarded response is not compressed right now~ EDIT: seems like we don't need to right now based on feedback
> feat: implement online style fetching for stable style resolving

- src/fastify-plugins/maps/index.js
- src/mapeo-manager.js
- test-e2e/manager-fastify-server.js
- tests/fastify-plugins/maps.js
- types/fastify.d.ts
Closes #438
Stacked on #435 
Notes:
- updates the maps fastify plugin to decorate the fastify instance with a `mapeoMaps` context, which currently implements a method for getting the style json url
- this PR does not actually implement the endpoint that handles the returned url. that will be addressed in https://github.com/digidem/mapeo-core-next/issues/439
> feat: add method to MapeoManager for getting stable map style json url

- types/brittle.d.ts
Noticed a couple of minor issues:
- types were not handling providing a promise (note, not a function returning a promise) as the first argument
- was noticing some misleading "unnecessary awaits" warnings in my editor, even though the provided function was async. narrowed it down to needing to adjust the order of the overload so that it was ordered from most specific to least specific (i.e. `() => Promise<unknown>` is a subset of `() => unknown`)
> chore: improve ExpectionAssertion type in Brittle TypeScript definitions

- src/sync/sync-api.js
- test-e2e/sync.js
> fix: emit sync state on sync.{start,stop}

- tsconfig.json
This enables the [strictFunctionTypes] TypeScript option, which brings us a little more type safety.
[strictFunctionTypes]: https://www.typescriptlang.org/tsconfig/#strictFunctionTypes
> chore: enable strictFunctionTypes TypeScript option

- package-lock.json
- package.json
- src/core-manager/index.js
- src/core-manager/remote-bitfield.js
- src/sync/core-sync-state.js
- src/sync/namespace-sync-state.js
- src/sync/sync-api.js
- src/sync/sync-state.js
- test-e2e/sync.js
- test-e2e/utils.js
- tests/remote-bitfield.js
- tests/sync/core-sync-state.js
- tests/sync/namespace-sync-state.js
Before starting sync of data, the sync state should accurately show the data that needs to be synced. There were bugs in the code that meant the "data to sync" was not accurate until the user had already started to sync the data. This PR fixes things so that after doing an "initial" sync, the sync state should accurately show how much data there is to be synced before the user starts syncing.
This PR fixes several things, because each fix revealed other bugs:
- Updates `RemoteBitfield` with changes from [upstream](https://github.com/holepunchto/hypercore/blob/fa23b5bcf5745dddaf607d92f8bccaa46a8642b1/lib/bitfield.js) to fix `findLast` and a few other things (data was not being added to the Quickbit index when it was inserted from a UInt32Array (as opposed to being set bit-by-bit).
- Fix …
> fix: sync state prior to full sync should be correct

- src/invite-api.js
- tests/invite-api.js
This primarily protects against incorrect usage.
> fix: throw if rejecting an invite that's already being accepted

- package-lock.json
- package.json
- src/invite-api.js
- tests/invite-api.js
This will make it possible for the frontend to sort incoming invites, and was requested by Erik.
> feat: add "received at" timestamp to invites

- src/schema/schema-to-drizzle.js
- tests/schema/schema-to-drizzle.js
This is a test-only change (other than tweaking a comment).
> chore: test jsonSchemaToDrizzleColumns

- src/schema/schema-to-drizzle.js
- tests/schema/schema-to-drizzle.js
_Depends on #530._
If we use the ["integer" JSON Schema type][0], we should save that as an INTEGER column, not a REAL column. Both will work for many numbers, but larger integers (like `2**63`) can only be safely stored in INTEGERs.  This should be a bit more reliable.
As of this patch, we don't have any integer types in our schemas, so this has no effect. However, that may change as we address [upcoming issues][1].
[0]: https://json-schema.org/understanding-json-schema/reference/numeric#integer
[1]: https://github.com/digidem/mapeo-core-next/issues/150
> chore: save schema integers in INTEGER SQLite columns

- test-e2e/project-crud.js
- test-e2e/utils.js
This is a minor test-only change.
We had two identical test helpers: `stripUndef` and `removeUndefinedFields`. This removes `stripUndef` and uses `removeUndefinedFields` everywhere.
> chore: remove redundant test helper

- package.json
This is a minor test-only change.
We don't need to test the `vendor/` directory because it doesn't exist.
> chore: don't run tests on missing vendor/ directory

- src/mapeo-manager.js
- test-e2e/manager-basic.js
`manager.createProject({ configPath: 'path/to/config.zip' })` creates a project with the specified config.
Closes #533.
> feat: create projects with non-default config

- test-e2e/utils.js
This is a test-only change that should have no impact.
`config.presets()`, `config.fields()`, and `config.icons()` are all iterables that we can convert to arrays.
> chore: shorten `getExpectedConfig`

- proto/rpc.proto
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- src/invite-api.js
- src/lib/ponyfills.js
- src/local-peers.js
- src/member-api.js
- test-e2e/manager-invite.js
- tests/helpers/events.js
- tests/invite-api.js
- tests/lib/ponyfills.js
*I recommend reviewing this PR one commit at a time.*
This PR adds invite cancelations. Notable changes:
- `InviteCancel` RPC messages are now sent and received.
- `project.$member.invite()` takes an `AbortSignal`, used for cancelations. It replaces the timeout option.
- The `invite-removed` event now has a "reason" parameter which the frontend can use.
Closes #447.
> feat!: invite cancelations

- test-e2e/project-leave.js
These tests have been very flaky. After a few hours of investigation it seems that peers weren't synced before someone left the project, which caused `waitForSync` to hang indefinitely.
We likely want our leave code to be more robust. In the short term, however, I think it's worth fixing these tests. (See https://github.com/digidem/mapeo-core-next/pull/469#issuecomment-2050255602 for these "make it more robust" tasks.)
Closes #540.
> chore: fix flaky "project leave" tests

- package.json
This makes two improvements to `lint-staged`:
- Run Prettier on all files, not just some extensions.
- Only check files, not fix them. This addresses a race condition (search [lint-staged's docs][0] for "race condition").
(I know there's some controversy about whether to use `lint-staged` at all, but I think these are improvements we can adopt regardless.)
[0]: https://www.npmjs.com/package/lint-staged
> chore: lint-staged improvements

- tests/config-import.js
Iterpal's `size` function can save us a few lines and avoid a few `eslint-disable`s.
> chore: use `size` helper in config import tests

- package-lock.json
- package.json
This updates TypeScript to its latest version, 5.4.5. It also required updating `typedoc`.
As far as I could tell, this made no meaningful changes to `dist/` and should be safe to do.
> chore: update TypeScript

- src/invite-api.js
- test-e2e/manager-invite.js
- test-e2e/utils.js
- tests/invite-api.js
When you accept an invite, we should return the project public ID.  Without it, the frontend has to pull it out of the invite object, which feels like an implementation detail to me and Erik.
> feat: return project public ID when accepting invite

- src/invite-api.js
- src/mapeo-manager.js
Simple logging for invites.
Closes #542.
> chore: add logging for invitees

- test-e2e/manager-restart.js
- test-e2e/utils.js
This test-only change creates a project. Then, it makes a new manager with the same files and asserts that the project is still there.
Because the only way to close a manager is to close the Node process, this test adds a bunch of scaffolding to do that.
> chore: test re-loading manager with the same data

- tests/sync/namespace-sync-state.js
This test-only change fixes a couple of small type errors in our tests for `NamespaceSyncState`.
> chore: fix type errors in NamespaceSyncState tests

- src/core-manager/index.js
- test-e2e/sync.js
In the following scenario:
1. Alice and Bob connect but do not start sync.
2. Alice adds an observation.
Bob should see that there is something new to sync.
Previously, this wouldn't happen. Now, when a writer core is appended to or cleared, we send new pre-have messages.
Closes #582.
> fix: update pre-haves as they change

- tests/bitfield-rle.js
These weren't needed, so we can just delete them.
I think this is a useful change on its own but it should also make it a little easier to switch to another test runner in the future.
> test: remove spurious uses of `t.end()`

- tests/sync/core-sync-state.js
We weren't using the right syntax to mark a string as const, so its type was `string` when we meant it to be `'auth'`. That caused a type error, which is fixed by this change.
> chore: fix const type error in sync test

- tests/sync/core-sync-state.js
We can't use bigint literals because we're targeting &lt;ES2020. We only did this in tests, which I fixed in this commit.
> chore: don't use bigint literals

- tests/fastify-plugins/blobs.js
This test-only, type-only change:
1. Fixes some type imports
2. Adds explicit parameters to a function that needed them
> chore: fix type errors in Fastify plugin blob tests

- src/discovery/local-discovery.js
- tests/discovery/local-discovery.js
`LocalDiscovery.prototype.address()` was only used by tests, so we can remove it and tweak the test.
> chore: remove unused `address` method from `LocalDiscovery`

- tests/core-manager.js
There are still a few errors in this file but this addresses many of them.
> chore: fix several type errors in core manager tests

- package.json
- src/mapeo-project.js
This enables the [ESLint eqeqeq rule][0], requiring `===` and `!==` over `==` and `!=`.
[0]: https://eslint.org/docs/latest/rules/eqeqeq
> chore: disallow `==` and `!=`

- src/sync/sync-api.js
_This change should have no impact._
`SyncApi` needs to know whether sync is enabled. Currently, it does this in a roundabout way: appending a value to a set and checking for that value.
This change replaces that with a simpler boolean flag.
I think this is a useful change on its own, but it'll be useful as part of #576 too.
> chore: simplify `SyncApi` "is syncing" logic

- tests/blob-store/combine-states.js
This is a test-only change that fixes the remaining type errors in this file.
> chore: fix type errors in blob store combineStates tests

- src/datatype/index.d.ts
- src/datatype/index.js
- src/mapeo-project.js
- tests/data-type.js
- tests/icon-api.js
- tests/translation-api.js
To be merged into #473.
`DataType` needs access to `TranslationApi.prototype.get`, but `TranslationApi` needs access to `DataType`. To avoid this circular reference, pass a `getTranslations` function into `DataType`.
> Fix "use before define" issue with DataType & TranslationApi

- package.json
- src/fastify-plugins/icons.js
This enables ESLint's [`default-case`][0] and [`default-case-last`][1] rules to ensure that all `switch` statements end with a `default`.
There was one spot where we weren't doing this, which I fixed.
[0]: https://eslint.org/docs/rules/default-case
[1]: https://eslint.org/docs/rules/default-case-last
> chore: require `default` case in `switch` statements

- package.json
- src/core-manager/index.js
- src/core-ownership.js
- tests/core-manager.js
This change should have no impact on functionality.
`node:assert` has two modes: [strict] and [legacy]. The latter can have some strange behavior. This adds an [ESLint rule][no-restricted-imports] to prefer the strict mode, and fixes all violations.
I think this is a useful change on its own but it should make it a little easier to drop Brittle in the future.
[strict]: https://nodejs.org/api/assert.html#strict-assertion-mode
[legacy]: https://nodejs.org/api/assert.html#legacy-assertion-mode
[no-restricted-imports]: https://eslint.org/docs/latest/rules/no-restricted-imports
> chore: prefer strict Node assert

- test-e2e/translation-api.js
To be merged into #473.
See [this comment](https://github.com/digidem/mapeo-core-next/pull/473/files/a51f709ca5edf7eec82c37ab922eab81433119c3#diff-8d53b37e24956c77fbf7b47691ded78c4b5c35010b94ad0b7e3d4dc49bcb6419).
> chore: fix type errors in translation api e2e test

- tests/datastore.js
This types-only change fixes the type errors in this file.
> chore: add types to fix datastore test type errors

- package-lock.json
- package.json
- src/sync/peer-sync-controller.js
- test-e2e/project-leave.js
_Depends on <https://github.com/digidem/digidem-types/pull/14>. We can't merge this until that's deployed._
If a core is closed, we can't replicate it.
This can happen if you leave a project while offline, then reconnect. I added a test for this case and fixed the issue. (The fix is just one line, but it took a whole day to figure that out.)
Fixes #584.
> fix: remove replication error when core is closed

- src/core-manager/index.js
Followup to 6ad3beaaff8d10d4a23a52380e73d8f76c833928. If we're adding lots of data at once (like during a config import), we shouldn't flood the network.
See [this comment](https://github.com/digidem/mapeo-core-next/commit/6ad3beaaff8d10d4a23a52380e73d8f76c833928#r141813463).
> chore: throttle pre-have updates to avoid network flooding

- package-lock.json
- package.json
I think this is a useful change on its own, but it will make our migration from Brittle to `node:test` easier because [`TestContext` is now exported][0], which we'll need.
[0]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69497
> chore: update @types/node to latest v18 version

- package-lock.json
- package.json
This updates dot-prop to its latest version, v9.0.0.
The only breaking change in [the release notes][0] doesn't affect us: Node 18+ is now required.
[0]: https://github.com/sindresorhus/dot-prop/releases/tag/v9.0.0
> chore: update dot-prop dependency to 9.0.0

- package-lock.json
Restores the inclusion of all platform-specific builds for `@node-rs/crc32`. Without this, I was not able to run the code locally (usually as tests) on macOS, with an error looking like this:
```sh
node:internal/modules/cjs/loader:1140
const err = new Error(message);
^
Error: Cannot find module '@node-rs/crc32-darwin-x64'
Require stack:
- /Users/andrewchou/GitHub/digidem/mapeo-core-next/node_modules/@node-rs/crc32/index.js
- /Users/andrewchou/GitHub/digidem/mapeo-core-next/node_modules/yauzl-promise/lib/zip.js
- /Users/andrewchou/GitHub/digidem/mapeo-core-next/node_modules/yauzl-promise/lib/index.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
at Module._load (node:internal/modules/cjs/loader:981:27)
at Module.require (node:internal/modules/cjs/loader:1231:19)
at …
```
> chore: fix lockfile to include platform builds of @node-rs/crc32

- .prettierignore
Seems like Prettier will completely ignore the `.gitignore` if `.prettierignore` also exists. Can apparently use both if you use the [`--ignore-path` CLI flag](https://prettier.io/docs/en/cli#--ignore-path)), but that doesn't seem ideal.
> chore: make prettier ignore coverage/ and proto/build/ directories

- tests/fastify-plugins/blobs.js
- tests/fastify-plugins/icons.js
- tests/fastify-plugins/maps.js
- tests/fastify-plugins/offline-fallback-map.js
- tests/fastify-plugins/static-maps.js
This test-only change drops Brittle from our Fastify plugin tests and replaces them with `node:test` and `node:assert`.
> test: move Fastify plugin tests to `node:test` and `node:assert`

- tests/bitfield-rle.js
_I recommend [reviewing this with whitespace changes disabled](https://github.com/digidem/mapeo-core-next/pull/636/files?w=1)._
This test-only change drops Brittle from our bitfield run length encoding tests and replaces them with `node:test` and `node:assert`.
> test: move bitfield-rle tests to `node:test`

- tests/blob-store/blob-store.js
- tests/blob-store/combine-states.js
- tests/blob-store/live-download.js
This test-only change drops Brittle from the blob store tests and replaces them with `node:test` and `node:assert`.
> test: move blob store tests to `node:test`

- tests/datastore.js
This test-only change drops Brittle from our DataStore tests and
replaces them with `node:test` and `node:assert`.
> test: move DataStore tests to `node:test`

- tests/data-type.js
This test-only change drops Brittle from our DataType tests and replaces them with `node:test` and `node:assert`.
> test: move DataType tests to `node:test`

- tests/blob-api.js
This test-only change drops Brittle from the blob API tests and replaces them with `node:test` and `node:assert`.
> test: move blob API tests to `node:test`

- tests/core-ownership.js
This test-only change drops Brittle from our core ownership tests and replaces them with `node:test` and `node:assert`.
> test: move core ownership tests to `node:test`

- tests/lib/hashmap.js
- tests/lib/ponyfills.js
- tests/lib/string.js
- tests/lib/timing-safe-equal.js
This test-only change drops Brittle from test/lib/ and replaces it with `node:test` and `node:assert`.
> test: move test/lib/ to `node:test`

- tests/utils.js
This test-only change drops Brittle from our utils tests and replaces
them with `node:test` and `node:assert`.
> test: move utils tests to `node:test`

- tests/sync/core-sync-state.js
This test-only change drops Brittle from our CoreSyncState tests and
replaces them with `node:test` and `node:assert`.
> test: move CoreSyncState tests to `node:test`

- test-types/schema.ts
- test-types/tsconfig.json
- tests/schema.js
This is a test-only change. `test-types/` is a better place for type tests.
See [this comment][0].
[0]: https://github.com/digidem/mapeo-core-next/pull/647#discussion_r1603406577
> test: move schema type tests to test-types/

- test-e2e/manager-basic.js
This test-only change drops Brittle from our basic manager tests and replaces them with `node:test` and `node:assert`.
Two notable things about this change:
1. There was a test that was commented out because of a Brittle bug.  This uncomments it and sets the `skip: true` option.
2. Brittle has an ([undocumented][0]) `t.snapshot()` method which we can't use. I replaced it with a custom snapshot assertion.
The rest was just mechanical stuff.
[0]: https://github.com/holepunchto/brittle/pull/45
> test: move basic manager tests to `node:test`

- test-e2e/manager-fastify-server.js
This test-only change drops Brittle from our Fastify server tests and
replaces them with `node:test` and `node:assert`.
> test: move Fastify server tests to `node:test`

- test-e2e/members.js
- tests/config-import.js
- tests/core-manager.js
- tests/discovery/local-discovery.js
- tests/local-peers.js
- tests/sync/namespace-sync-state.js
- types/brittle.d.ts
We plan to replace Brittle with `node:test` which doesn't have an equivalent for `t.plan`. Remove it to make it easier to migrate.
Notably, this removes `t.plan` from the type definitions to discourage its use.
> test: remove `t.plan()` calls

- src/mapeo-manager.js
- test-e2e/utils.js
This change should have no impact.
This property was never used, so we can remove it.
> chore: remove unused "device type" property from MapeoManager

- tests/config-import.js
This test-only change drops Brittle from our config import tests and replaces them with `node:test` and `node:assert`.
> test: move config import tests to `node:test`

- src/core-manager/bitfield-rle.js
- tests/bitfield-rle.js
This fixes all the type errors in the tests for `bitfield-rle`. Some of the type errors were entirely test-only, but others required changes to the "real" code. Most notably, many `Buffer` types were changed to `Uint8Array`.
> chore: fix type errors in bitfield-rle tests

- tests/core-manager.js
- types/corestore.d.ts
These types were wrong which caused type errors in tests.
Once this is fixed, we can start type-checking tests (which we currently don't).
> chore: fix types for Corestore.prototype.replicate

- tests/tsconfig.json
- tsconfig.json
_This only affects type-checking in tests and should have no user
impact._
Before this change, we weren't type-checking the `tests/` folder. Now we
are!
Prerequisites that made this change possible (list might be incomplete):
- ebcd4d2f9ec33f05f2f681f0fcf4d03c6b8e1401
- df666568383e50bccf4d87edf85b58ae917be0d5
- 91d8c9ce97ce2df15a9cacf4110caa45464baf97
- eca4741c5ce22c6720f1ccd5a329684db7ee86ff
- f64ca17daf646e8fd0e2dca2bad63e464aec21ab
- 0d3d8d93fa531c45f5a48ed9bb410481050461ef
- 57cfe729f933236dd0cc8e568eed364bd83bb0f0
- 95a1fa9bf1e7e38577ba8d892ab4417767ac539e
- b7226aa73dfc153302b00856b5b3e4a28cd660f9
- 0121b2d8281e282232db8dc0d43d597fafc93d23
- 079c7e57674a6509a035e90bb9bac3542870521a
- d7b0268293c81e6fefc7fd79a3e0fbb1ee33dde6
- 3bb941f6916108ea7308d09e04c514b2d8353303
- …
> chore: enable type checking for all tests

- tests/icon-api.js
This test-only change drops Brittle from our icon API tests and replaces them with `node:test` and `node:assert`.
> test: move icon API tests to `node:test`

- src/core-manager/index.js
We were effectively doing something like this:
```javascript
if (!object) {
console.warn('no object', object.propertyAccessThatWillFail)
}
```
This could throw an error because we can't access properties on `null` or `undefined`.[^0]
This updates the log message to avoid this error.
[^0]: It's possible that the value was another falsy value, such as `false`, where you can technically access properties. I still think this change is an improvement in that situation, because `false.remotePublicKey` is `undefined`, which isn't very useful.
> chore: don't error when calling `#sendHaves` without a peer

- tests/helpers/core-manager.js
*This is a test-only change.*
`tests/helpers/core-manager.js` wasn't type checked because it had a `// @ts-nocheck` at the top. This removes that check and fixes all the type errors.
This mostly required adding type annotations, but a few changes were a little more involved.
> chore: type-check core manager test helpers

- tests/sync/namespace-sync-state.js
This test-only change drops Brittle from our namespace sync state tests
and replaces them with `node:test` and `node:assert`.
> test: move namespace sync state tests to `node:test`

- test-e2e/sync.js
*I recommend [reviewing this with whitespace changes disabled](https://github.com/digidem/mapeo-core-next/pull/689/files?w=1).*
This speeds up our "create and sync data" test. On my machine, it went from ~73 seconds to ~12.
I did this by making a few changes:
- Decrease the number of managers from 10 to 5, dramatically reducing the amount of connections required. I don't think 10 really offers much here, other than perhaps a stress test, and lowering it offers a huge speedup.
- Run assertions concurrently.
- When comparing sets, use `Set` instead of sorted arrays. This speeds things up a bit.
- Use `node:assert` instead of Brittle for a slight performance boost.  We also plan to drop Brittle in the future and this will ease the transition.
Each of these could theoretically be done …
> test: speed up "create and sync data" test

- src/sync/sync-api.js
- test-e2e/sync.js
`myProject.$sync.start({ autostopDataSyncAfter: 3000 })` will auto-stop data sync after it's inactive for 3 seconds.
Addresses #627.
> feat: add auto-stop option to `$sync.start()`

- src/mapeo-manager.js
- src/mapeo-project.js
- test-e2e/project-leave.js
If you start to leave a project and the operation fails partway, we now finish the next time you try to load that project.
For example, imagine the following scenario:
1. The user presses the "leave project" button.
2. We mark them as having left the project, but haven't yet deleted any data.
3. Their phone runs out of battery.
Previously, the project state would be messed up in this scenario. Now, we finish the cleanup before returning the project.
Fixes #583.
> fix: at startup, clean up left projects that failed to delete

- .github/workflows/release.yml
[`npm ci`][0] is slightly better for deployments than `npm install`.
- It ensures all installed packages match `package-lock.json`.
- It automatically removes `node_modules/` if it exists, ensuring a clean slate.
- It won't update `package.json` or `package-lock.json`.
Not a huge difference, but recommended for deployments.
[0]: https://docs.npmjs.com/cli/v10/commands/npm-ci
> chore: use `npm ci` for deployment, not `npm install`

- test-e2e/local-peers.js
- test-e2e/manager-invite.js
- test-e2e/members.js
- test-e2e/project-leave.js
- test-e2e/sync.js
- test-e2e/utils.js
We want to disconnect managers at the end of tests. This moves that to a `t.after()` call so that it will run whether the test passes or fails.
> test: disconnect managers in teardown, not inline

- tests/blob-store/blob-store.js
This is a very minor change.
The `testenv` helper was async but didn't need to be. I think this change makes the test slightly clearer, and also saves ~52 milliseconds on my machine.
> test: make blob store test helper synchronous

- .github/workflows/release.yml
This is currently broken but we want to do a release.
In the long term, we'll fix this (see #707). In the short term, we disable this.
> docs: disable doc build when releasing

- package.json
- src/blob-store/index.js
- src/blob-store/live-download.js
- src/config-import.js
- src/core-manager/core-index.js
- src/logger.js
- test-e2e/translation-api.js
- tests/fastify-plugins/blobs.js
- tests/fastify-plugins/static-maps.js
- tests/sync/core-sync-state.js
This enables the [ESLint `curly` rule][0] to enforce the use of curly brackets when the block contains multiple lines.
After reading a bunch of our code, this intends to make explicit an implicit part of our code style.
[0]: https://eslint.org/docs/latest/rules/curly
> chore: require curly brackets for multiline blocks

- src/index.js
- test-e2e/manager-invite.js
- test-e2e/utils.js
You can now import `CREATOR_ROLE_ID`, `COORDINATOR_ROLE_ID`, and `MEMBER_ROLE_ID`.
```javascript
import { roles } from '@mapeo/core'
myProject.$member.invite(deviceId, { roleId: roles.MEMBER_ROLE_ID })
```
CoMapeo Mobile [currently hard-codes these values][0].
Note that "weirder" IDs, like `LEFT_ROLE_ID`, are deliberately *not exported right now* because they're easy to add later if needed.
Closes #532.
[0]: https://github.com/digidem/comapeo-mobile/blob/2cfa789360a2faa066a85fde8aad73d5e80a5dfd/src/frontend/sharedTypes/index.ts#L31-L37
> feat: expose creator, coordinator, and member role IDs

- src/discovery/local-discovery.js
If two peers connect and one disconnects, the other won't necessarily know.
1. Alex and Charlie connect. Alex sees that they are connected to 1 device.
2. Charlie disconnects from wifi. Alex still sees a connection to 1 device, even though the connection should be broken.
We can fix this in several ways. I think the best is to enable [TCP keepalive], which effectively sends a packet every second asking, "is this connection still on?".
I did not add unit tests for this (I could not think of a good way) but did test manually in CoMapeo with two Android devices.
[TCP keepalive]: https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html
> feat: detect closed connections with TCP keepalive

- src/mapeo-project.js
*This change should have no user impact.*
`#ownershipWriteDone` was never used, so we can remove it.
(It's still used in `CoreOwnership` but that's completely separate.)
> chore: remove unused member from `MapeoProject`

- src/core-manager/index.js
- test-e2e/sync.js
Media isn't syncing. This seems to be because we hard-coded the `blob` namespace not to auto-download. This removes that and adds an automated test to check it.
I don't know why we did this, but it seems to have originated in [a 2023 commit][0] (later updated in [another commit][1]).
Should address [comapeo-mobile#514].
[0]: https://github.com/digidem/mapeo-core-next/pull/362/commits/5a47b569b6ad7b417fb866f2c518626fca9b39ad
[1]: https://github.com/digidem/mapeo-core-next/commit/ea442a35ef7113dd98dcb3bd984739f333e314f3
[comapeo-mobile#514]: https://github.com/digidem/comapeo-mobile/issues/514
> fix: auto-download blob namespace

- src/sync/sync-api.js
- test-e2e/sync.js
We didn't correctly emit `state.data.isSyncEnabled` right after starting or stopping; you needed to call the function twice to make it emit the correct state.
This fixes that by emitting the event at a more correct time.
> fix: properly emit sync state right after starting/stopping

- src/sync/core-sync-state.js
*This change should have no impact and is not urgent.*
I noticed this unused cache while working on [#724]. It's safe to remove because it's never used.
If we find performance issues in this class, we can always come back and re-add a (working) cache.
[#724]: https://github.com/digidem/mapeo-core-next/issues/724
> chore: remove unused cache from `CoreSyncState`

- src/blob-api.js
- test-e2e/manager-fastify-server.js
- tests/blob-api.js
- tests/helpers/blob-store.js
This adds support for two additional blob metadata fields: location and timestamp.
This works when tested against [this CoMapeo PR][0], which sets those fields but has to ignore type errors.
Closes #719.
[0]: https://github.com/digidem/comapeo-mobile/pull/532
> feat: support additional metadata for blobs

- test-e2e/sync.js
*This is a test-only change.*
I should have rebased/merged `main` before merging e16bee96e99a1bdb2333a35e10b3028c76c36dfc.
e16bee96e99a1bdb2333a35e10b3028c76c36dfc updated the types for `project.$blobs.create()`. That commit was written before f5591d5cbc36cf64452aef0612666748e7248634 was merged, which called that function. Merging e16bee96e99a1bdb2333a35e10b3028c76c36dfc caused a type error.
This fixes all of that.
> chore: fix type error in sync test

- src/blob-store/live-download.js
- src/core-manager/bitfield-rle.js
- src/core-manager/index.js
- src/core-manager/remote-bitfield.js
- src/discovery/local-discovery.js
- src/mapeo-project.js
- test-e2e/utils.js
- tests/core-manager.js
- tests/helpers/core-manager.js
*This is a minor, JSDoc-only change.*
`@returns` by itself doesn't do much in JSDoc. This either removes those directives or adds their return type.
> docs: remove useless `@returns` from several functions

- src/sync/sync-api.js
- test-e2e/sync.js
`project.$sync.setAutostopDataSyncTimeout(1234)` sets the auto-stop timeout to 1234 milliseconds without changing the enabled state of sync.
Closes #746.
> feat: add API to change sync auto-stop timeout

- .gitignore
This fixes a minor issue from 1c097ee1a3f5d3425824a4b8d846c59350aeb567: ZIP fixtures weren't properly ignored.
> chore: ignore test fixture ZIPs

- src/blob-store/index.js
- src/config-import.js
- tsconfig.json
This change should have no user impact.
`Object.hasOwn()` replaces `Object.prototype.hasOwnProperty()` in modern JavaScript. Its advantages can be seen in the following code snippet:
```javascript
// Still works even if you overwrite `hasOwnProperty`:
const overwritten = { hasOwnProperty: () => true }
Object.hasOwn(overwritten, "foo")
// => false
overwritten.hasOwnProperty("foo")
// => true (incorrect)
// Still works even if the object has a null prototype:
const nullPrototype = Object.create(null)
nullPrototype.foo = "bar"
Object.hasOwn(nullPrototype, "foo")
// => true
nullPrototype.hasOwnProperty("foo")
// TypeError: nullPrototype.hasOwnProperty is not a function
```
This replaces all uses of `Object.prototype.hasOwnProperty()` with `Object.hasOwn()`.
I think this is a useful change on …
> chore: use `Object.hasOwn()`

- src/core-manager/index.js
- src/sync/core-sync-state.js
- src/types.ts
*This is a types-only change.*
Before this change, we used `any` for a Hypercore peer's type.
After this change, we use a new type, `HypercorePeer`, designed to match [Hypercore's `Peer` class][0].
Ideally, we would put this in `@digidem/types` or DefinitelyTyped. For now, I think this is an improvement over the `any`s we currently use.
I did this because I'm working with peer-related code and found the `any`s difficult to work with.
[0]: https://github.com/holepunchto/hypercore/blob/de993dc051301f03570df0eb7929c06286745563/lib/replicator.js#L331
> chore: improve types for Hypercore peers

- package-lock.json
- package.json
- src/sync/core-sync-state.js
- src/sync/namespace-sync-state.js
- src/sync/peer-sync-controller.js
- src/sync/sync-api.js
- test-e2e/sync.js
- tests/sync/core-sync-state.js
- tests/sync/namespace-sync-state.js
`myProject.$sync.getState()` and the `sync-state` event now return objects like this:
```javascript
{
initial: { isSyncEnabled: true },
data: { isSyncEnabled: true },
remoteDeviceSyncState: {
abc123: {
initial: { isSyncEnabled: true, want: 0, wanted: 0 },
data: { isSyncEnabled: true, want: 2, wanted: 0 },
},
def456: {
initial: { isSyncEnabled: true, want: 0, wanted: 0 },
data: { isSyncEnabled: true, want: 0, wanted: 1 },
},
},
}
```
In English, this means:
- We now have sync information for individual peers, instead of aggregated info.
- `want` and `wanted` have slightly different meaning than before. `want` is the number of blocks a peer wants from us, and `wanted` is the number of blocks we want from a specific peer.
For example, imagine peers A, B, and C are connected and syncing. Peer …
> feat!: expose device-specific sync state

- package-lock.json
- package.json
- test-e2e/project-crud.js
Notably for us, TypeScript 5.5 introduces the [`@import` JSDoc tag][0], which we can start using.
This required us to upgrade Typedoc and fix a small type error.
[0]: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-jsdoc-import-tag
> chore: update TypeScript to 5.5

- src/core-ownership.js
We want to call a function once the auth writer core emits its `ready` event. Using `once` lets us clean up the listener once it fires, rather than leaving it around.
Extracted from #390.
> chore: only write auth writer core once in CoreOwnership

- src/core-manager/core-index.js
- src/core-manager/index.js
- src/core-ownership.js
- src/mapeo-manager.js
- src/mapeo-project.js
- src/roles.js
- src/sync/core-sync-state.js
- src/sync/namespace-sync-state.js
- src/sync/peer-sync-controller.js
- src/sync/sync-state.js
- src/types.ts
- tests/core-manager.js
- tests/core-ownership.js
The `Namespace` type is pretty central, but was stuffed away in `core-manager/index.js`. Its type was also inferred in many cases.
Now it's in a more central spot: `types.ts`.
I think this is useful on its own, but it should make a future change easier.
> chore: use standard Namespace type

- types/protomux.d.ts
Several Protomux methods support `null` IDs ([`pair`, for example][0]). This updates our type definitions to reflect that.
I think this is a useful change on its own, but may make upcoming changes easier too.
[0]: https://github.com/holepunchto/protomux/blob/ca7f9aeba40b0e042383728fa063f984028362be/index.js#L315
> chore: allow `null` in several Protomux method options

- test-e2e/core-ownership.js
- test-e2e/created_by_to_device_id.js
- test-e2e/project-leave.js
Our tests have several spots where we create mock data, such as observations or presets. We typically rely on `@mapeo/mock-data` for this, but could use it in a few more places. That's what this commit does!
I think this is useful for three reasons:
1. It's less code.
2. It doesn't need to be manually updated when we make schema updates.
3. It will make [an upcoming change][0] smaller.
[0]: https://github.com/digidem/mapeo-core-next/pull/715
> test: use mock data in more places

- package-lock.json
- package.json
This dependency seems unused, so we can remove it.
It looks like it was added in 8e64abdf736b31d1a13a1d9791fd9f677118d8d2 but never used.
> chore: uninstall unused light-my-request dependency

- package-lock.json
- package.json
Removing this has two benefits:
1. This simplifies the install for dependents. For example, the frontend has needed to patch itself `@mapeo/core` in the past.
2. The usual benefits of removing a dependency: decreased file size, smaller attack surface, etc.
We can always add it back if we need it again.
> chore: remove unused patch-package dependency

- CONTRIBUTING.md
- package-lock.json
- package.json
`hyperswarm` is no longer used, so we can remove it.
Note that we still use `@hyperswarm/secret-stream` in this project.
> chore: remove unused `hyperswarm` dependency

- src/core-ownership.js
- src/datatype/index.d.ts
- src/datatype/index.js
- src/roles.js
This is part of the solution for #268.
> feat: emit updates from CoreOwnership and Roles, add CoreOwnership#get

- src/mapeo-manager.js
- test-e2e/manager-basic.js
You can now create a project and set its "is initial project?" value, like so:
```js
const projectId = manager.createProject({ isInitialProject: true })
```
> feat: create projects as initial project

- src/sync/core-sync-state.js
- src/sync/namespace-sync-state.js
- src/sync/peer-sync-controller.js
- src/sync/sync-api.js
- tests/sync/core-sync-state.js
This is just a rename, which is a bit more correct.
Because Gregor and I paired on this, I plan to merge it with no review.
> chore: rename `PeerCoreState` to `PeerNamespaceState`

- package-lock.json
For some reason, I accidentally removed some macOS-only subdependencies of `yauzl-promise` in 05644802113ac2a2c1b6ee932dca8d99c59d65af. This reinstalls `yauzl-promise` to re-introduce those.
> chore: reinstall `yauzl-promise` to fix subdependency error

- tests/helpers/core-manager.js
_This change is not urgent._
This is just a simple rename for clarity. See [this comment][0].
[0]: https://github.com/digidem/mapeo-core-next/pull/783#pullrequestreview-2266845710
> test: rename CoreManager test helper function name and args

- src/sync/sync-api.js
This change should have no impact on functionality.
`SyncApi`'s `#peerIds` member was written but never read. This removes it.
> chore: remove unused member from `SyncApi`

- src/sync/core-sync-state.js
- src/sync/namespace-sync-state.js
- src/sync/peer-sync-controller.js
- src/sync/sync-api.js
- tests/sync/core-sync-state.js
- tests/sync/namespace-sync-state.js
This change should have no impact on functionality. This came up while @gmaclennan and I were pairing.
This renames the options for `PeerNamespaceState#status`:
- `disconnected` → `stopped`
- `connecting` → `starting`
- `connected` → `started`
> chore: rename peer namespace state status options

- src/sync/sync-api.js
Imagine the following scenario:
- *auth* namespace sync is enabled.
- *config* namespace sync is disabled.
- *blobIndex* namespace sync is enabled.
Previously, this would report the initial namespace sync state as *enabled*. Now, this will report *disabled*, because every namespace needs to be on.
> fix: only mark sync state enabled when entire group is enabled

- package-lock.json
- package.json
This updates hypercore-crypto to its latest version.
This project has no changelog but [perusing the commits][0] shows:
- Sub-dependency upgrades
- Minor security and performance improvements
[0]: https://github.com/holepunchto/hypercore-crypto/commits/main
> chore: update hypercore-crypto to 3.4.2

- tests/config-import.js
This happened in dfd7632344c7a66f3427398e36021d271ef7b00e. Presumably, I was trying to find-replace `t.is` with `assert.equal` and the regex was too broad.
I plan to merge this without review if CI passes.
> test: fix config import assertion message typo

- package-lock.json
- package.json
- src/datatype/index.js
- test-e2e/project-crud.js
This updates `@mapeo/schema`, and related dependencies, to the latest version.
This changed two things:
- `Observation`s now require `lat` and `lon` again
- `Track`s no longer have attachments
> feat!: update `@mapeo/schema` to latest version

- proto/rpc.proto
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- src/mapeo-manager.js
this is a regression from previous release of core. 
We originally added `selfHostedServer` to `DeviceInfo.deviceType` to match schema definition. But we don't want to be able to open rpc connections to a remote server; so instead we just mangle the types to omit that enum member were appropiate
> fix: remove `selfHostedServer` from `deviceInfo.deviceType` rpc

- package-lock.json
- package.json
- types/compact-encoding.d.ts
- types/protomux.d.ts
[`@types/compact-encoding`][0] was recently published. Let's use that instead of our "empty" type.
[0]: https://www.npmjs.com/package/@types/compact-encoding
> chore: use upstream types for `compact-encoding`

- src/discovery/local-discovery.js
- tests/discovery/local-discovery.js
This change should have no functionality impact.
`LocalDiscovery.prototype.publicKey` and `.connections` were unused, so we can remove them. (There was technically a test that used one of them, but that was easy to change.)
> chore: remove unused `LocalDiscovery` members

- src/discovery/local-discovery.js
*This change should have no impact on functionality.*
Our local TCP socket error handler was typed with an `any` parameter but could easily be typed with an `Error` instead. This changes that.
> chore: use more exact type in socket error handler

- src/discovery/local-discovery.js
- src/lib/noise-secret-stream-helpers.js
- src/local-peers.js
- src/mapeo-manager.js
- src/sync/peer-sync-controller.js
- src/sync/sync-api.js
- src/utils.js
- tests/discovery/local-discovery.js
This change should have no impact on functionality.
This change creates `src/lib/noise-secret-stream-helpers.js`. It moves `openedNoiseSecretStream()` and two types in there.
It also tweaks the types for `OpenedNoiseStream` and `DestroyedNoiseStream`.
I think this is a useful change on its own but may also make an upcoming change easier.
> chore: use separate helper file for NoiseSecretStreams

- .github/workflows/release.yml
Since the idea is to follow semver, I've went ahead and only allowed (and uncommented) `patch`, `minor` and `version` on semver options. We may disagree with this and still have a prerelease (but I think we may not want this). 
Also I commented some traces of `prerelease` related to naming the release on github and npm. If approve, I'll remove those commented lines
> chore: semver on release flow

- src/discovery/local-discovery.js
*This is a types-only change.*
> chore: add explicit return types for `LocalDiscovery` methods

- .github/workflows/release.yml
I want to make a prerelease version.
> build: re-enable prerelease tags

- package-lock.json
- package.json
This is the cause of bugs in the v1.0.0 release candidate. The `corestore` dependency should have been pinned to the exact version that we are testing here (v6.8.4), but it was not.
The mobile app had already been using `corestore@6.15.9`, which had changed the hypercore dep to `hypercore@10.29.0`. This appeared to still work, to some extent. Commit https://github.com/digidem/comapeo-mobile/commit/e06a7e4554f1ac8f47f5bb407d328bf37f8919cb included a `src/backend/package-lock.json` change that changed the corestore dep to `corestore@6.18.4` and its subdep to `hypercore@10.37.22`.
Unfortunately we rely on hypercore internals, and in addition hypercore is not completely stable across minor versions, so changes to the hypercore version break things. We have thorough tests on comapeo-core to …
> fix: pin `corestore` dep to exact 6.8.4

- src/lib/hashmap.js
This types-only change removes a custom `Primitive` type in favor of type-fest's.
We defined them the same way so it shouldn't make a difference.
*I plan to yolo-merge this when CI passes.*
> chore: use `Primitive` type from type-fest

- src/sync/namespace-sync-state.js
*This change should have no user impact.*
`createState()` is never called with an argument, so we can remove the function and inline it.
> chore: remove unnecessary helper from namespace sync state

- src/mapeo-project.js
- src/translation-api.js
- tests/data-type.js
- tests/translation-api.js
`TranslationApi` was storing a property called `#table` which was never used. This removes it.
> chore: remove unused property from translation API

- .github/workflows/lockfile.yml
Uses a fork (https://github.com/rvanvelzen/npm-lockfile-changes) of the original action (https://github.com/codepunkt/npm-lockfile-changes) because the original does not seem to work with v3 lockfiles.
Uses the action's default values for inputs for now (https://github.com/marketplace/actions/npm-lockfile-changes#-inputs)
Also omits the `permissions` configuration since we don't use dependabot (https://github.com/marketplace/actions/npm-lockfile-changes#the-action-fails-on-the-dependabot-pull-requests). My understanding is that we don't need to specify as a result, but could be wrong.
Out of scope, but also updated this workflow to only run when the pull request changes the `package-lock.json` file, as opposed to anytime a pull request is opened. Happy to revert if not desired.
> chore: integrate npm-lockfile-changes action

- src/utils.js
`utils.js` exported `idToKey` and `parseVersion`, neither of which are used anywhere. This removes them.
> chore: remove unused utils

- .github/workflows/release.yml
Does a couple of things:
- Makes sure the pull request is targeting the main branch. Not sure if there are cases where we want this thing to run when that isn't the case
- Makes sure that the pull request is actually merged. Before, the workflow was being run when closing a pull request (and not merging), which adds more noise than necessary
> chore: only attempt to run release workflow when merging PR

- src/fastify-controller.js
In Node 18, calling `HTTP.Server.close()` does not close idle connections, which resulted in some undesirable behavior in the server lifecycle in CoMapeo Mobile (see https://github.com/digidem/comapeo-mobile/pull/748 for more context). In Node >=19, closing the server does the equivalent work of of `closeIdleConnections()` internally.
This PR explicitly calls `closeIdleConnections()` when stopping the server, at the guidance of the [Node docs](https://nodejs.org/docs/latest-v20.x/api/http.html#servercloseidleconnections):
> Starting with Node.js 19.0.0, there's no need for calling this method in conjunction with server.close to reap keep-alive connections. Using it won't cause any harm though, and it can be useful to ensure backwards compatibility for libraries and applications that need …
> fix: close idle connections when stopping FastifyController

- package-lock.json
- package.json
This change should have no user impact.
This updates TypeScript to the latest version, 5.6.2. It also updates `typedoc` dependencies to their latest versions.
I verified that the generated types in `dist/` were not meaningfully changed. (Some `Iterator` types were slightly adjusted, as expected; [TypeScript 5.6 made some changes to how `Iterator` types work][0].)
[0]: https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#iterator-helper-methods
> chore: update to TypeScript 5.6

- test-e2e/utils.js
`waitForPeers`, a test helper, currently checks that the *number* of connected peers is expected. This has two problems:
- If the number of connected peers is *more than needed*, it will never resolve.
- If the *number* of connected peers is correct but the actual peers are different, the promise could resolve prematurely.
This snippet highlights the problem:
```javascript
const managers = await createManagers(3, t)
const [a, b, c] = managers
connectPeers(managers)
await waitForPeers([a, c])
```
I think this is a useful change on its own, but will also make [an upcoming change][0] easier.
[0]: https://github.com/digidem/comapeo-core/pull/865
> test: be more exact when waiting for peers

- test-e2e/sync.js
We test that blocked members shouldn't be able to sync. However, it's possible that this test had false positives if the blocked member was simply missing from the project entirely!
This adds two assertions to make sure that the other members see the blocked one, and that they are indeed blocked.
> test: additional assertions in "blocked from sync" test

- src/lib/key-by.js
- src/member-api.js
- tests/lib/key-by.js
Previously, `MemberApi.prototype.getMany` would iterate through `allDeviceInfo` for every role.
Now, it only iterates through `allDeviceInfo` once.
> perf: speed up member list function

- src/member-api.js
- test-e2e/utils.js
We have a test helper, `invite`, that invites people to projects. It works like this:
1. Tell the invitee(s) to accept any invite they receive.
2. Send the invite.
This is fine for most of our tests, where only one invite will be sent to each manager. But we have [at least one test][0] where multiple invites are sent.
That can cause a race condition. Imagine the following scenario where `invite` is called twice:
1. Tell the invitee to accept any invite they receive (listener 1).
2. Tell the invitee to accept any invite they receive (listener 2).
3. Send the first invite.
4. Both listeners fire, sending one valid "accept" response and one that gets dropped.
4. Send the second invite. There are no listeners, and the test hangs.
This commit changes `invite`. Now, it works like this:
1. …
> test: fix race condition if multiple invites are sent

- test-e2e/project-crud.js
Our project CRUD tests had a number of `ts-ignore`s and `any`s. This replaces those with type-safe code.
I think this is a useful change on its own but will also make [an upcoming change][0] easier.
[0]: https://github.com/digidem/comapeo-core/pull/805
> test: improve type safety of project CRUD tests

- src/server/routes.js
This is a minor change. I think it makes sense to use `await` in an async function, rather than using `then` to handle the promise.
(I guess we're `await`ing in either case, but I think this is clearer.)
> chore: use `await` instead of `then` in server route

- package-lock.json
- package.json
For reasons unknown to me, `npm run protobuf` was failing due to this being out of date. I assume this was because of our recent TypeScript upgrade, but I did not investigate. In any case, updating fixes it and is a worthwhile change regardless.
> chore: update `@types/node` to latest 18.x version

- package-lock.json
- package.json
This updates `@hyperswarm/secret-stream` to the latest version.
I think this is a useful change on its own but is also useful as part of our upcoming cloud server work.
> chore: update `@hyperswarm/secret-stream` to 6.6.3

- src/local-peers.js
- src/types.ts
We import the `NoiseStream` type in a bunch of places. Typically, we import it from the source: `@hyperswarm/secret-stream`. This fixes one occurrence of a spot where we *didn't* do that, and we exporting it via a types utility file.
> chore: use consistent `NoiseStream` imports

- .github/workflows/lockfile.yml
This proposed change is to the lockfile bot which comments on pull requests with changes to the lockfile. I propose changing the bot config to update the original comment when the PR is updated, rather than creating new comments, in order to reduce "noise" in the PR comment thread. Open to arguments for keeping it as-is with new comments for each commit!
> chore: change lockfile bot to update comments

- package-lock.json
- package.json
- src/core-manager/index.js
- src/index-writer/index.js
- src/logger.js
- src/mapeo-manager.js
- src/mapeo-project.js
- src/sync/peer-sync-controller.js
- src/sync/sync-api.js
Several improvements to debug logging, to improve our ability to parse the logs and gather useful information:
- Fix a memory issue in the `PeerSyncController` logger, that was creating a new `Debugger` instance (by calling `Logger.create()`) each time anything was logged.
- Fixed a memory issue in `PeerSyncController` which was adding a `peer-remove` event listener every time a core is replicated, and never removing the listener. This was solely for debugging. Now only adds the listener if debugging is enabled.
- Log the namespace of cores that are replicated or unreplicated.
- Change the function signatures in `PeerSyncController` and expose the `CoreRecord` of the creator core, to enable this namespace logging.
- Removed unnecesary logging when handling discovery keys in …
> chore: debug logging improvements

- src/sync/core-sync-state.js
- src/sync/namespace-sync-state.js
- src/sync/sync-api.js
- src/sync/sync-state.js
- test-e2e/sync.js
There are two scenarios where a disconnected peer results in sync never showing as complete.
**Scenario A**:
1. 3 or more peers are connected.
2. A peer disconnects (e.g. wifi off)
3. Remaining peers add data (including inviting another device)
4. Any peer that was previously connected to the peer that disconnected thinks that the disconnected peer still "wants" data, so sync never completes.
**Scenario B**:
1. 3 or more peers are connected
2. A peer adds some data that is not synced (e.g. adds an observation while sync is not enabled)
3. That peer disconnects
4. Remaining peers attempt to sync.
5. Sync never completes because peers are waiting for data from disconnected peer.
Note that these bugs affect `project.$sync.waitForSync()`, which I don't think the front-end is not currently …
> fix: sync state with disconnected peers (take 2)

- src/server/allowed-hosts-plugin.js
- src/server/app.js
- src/server/base-url-plugin.js
- src/server/comapeo-plugin.js
- src/server/routes.js
- src/server/server.js
- src/server/types.ts
- test-e2e/server-integration.js
- test-e2e/server.js
This removes the server option `serverPublicBaseUrl` and instead uses the hostname from the `Host` header (or `X-Forwarded-Host` if [`trustProxy`](https://fastify.dev/docs/v4.28.x/Reference/Server/#factory-trust-proxy) is enabled).
The reason for this change is to simplify server configuration and avoiding errors stemming from the server value not matching the URL the server is accessible on.
The `Host` header is required by the HTTP 1.1 spec, so will always be present and can be trusted. We use the value that the client sends when creating a project, so the value used will be the value the client enters when they add the server.
> feat: use req.hostname instead of manually configured server host.

- .github/workflows/release.yml
I *think* this will fix the errors we're seeing on `release` CI.
See [the optic-release docs][0].
[0]: https://github.com/nearform-actions/optic-release-automation-action/blob/2bdd6c56fa196bd0c8f4f5a4374fc39b3ff78c8a/action.yml#L13-L15
> build: move doc building into same step as release

- src/member-api.js
- src/sync/sync-api.js
Not sure the best way to address this, but currently we aren't listening to the `error` event on websocket instances, which means that any errors raise an uncaught exception and crash the app. This should fix that for now.
> fix: avoid uncaught websocket errors

- src/fastify-plugins/maps.js
- src/fastify-plugins/utils.js
- test/fastify-plugins/maps.js
Closes #827 
Stacked on #896 
- adds a GET endpoint for the maps plugin located at `<prefix>/custom/info` to provide the name, size, and creation time of the custom map file if it exists
> feat: add endpoint for maps plugin to get info about custom map

- src/config-import.js
- src/core-ownership.js
- src/lib/omit.js
- src/mapeo-manager.js
- src/mapeo-project.js
- src/translation-api.js
- src/utils.js
- test/datastore.js
- test/lib/omit.js
- test/translation-api.js
*This PR is not urgent.*
This change should have no impact on functionality.
This replaces the following pattern:
```javascript
// eslint-disable-next-line no-unused-vars
const { foo, bar, ...rest } = obj
return rest
```
With a new `omit` utility, which I think is clearer:
```javascript
return omit(obj, ['foo', 'bar'])
```
I think this is a useful change on its own, but also makes an upcoming change slightly easier because I wanted this function.
> chore: add `omit` utility

- .github/workflows/release.yml
The optic release option `sync-semver-tags` creates additional tags (`v{MAJOR}`, `v{MAJOR}.{MINOR}`) which are updated on each release. This currently does not work because this tag push happens with the permissions of the default github actions token, which does not have rule bypass permissions. It's a "soft fail" (the release still gets made), and the full version tag comes from the release creation, which is done by the optic release app, which is included in our ruleset bypass list.
We don't need these tags, and they are not working, so this PR turns this option off.
> chore: don't sync semver tags for releases

- test-e2e/manager-fastify-server.js
This is a test-only change.
According to [Apache's list][0], the correct MIME type for `.mp3` files is `audio/mpeg`, not `audio/mp3`.
[0]: https://github.com/apache/httpd/blob/f5c4355420d4463c860aa0d85757bfb7a2dd0a40/docs/conf/mime.types#L1441
> test: use correct MIME type for MP3

- package-lock.json
- package.json
Our range for `fastify` caused fresh installations of this package to install fastify v5, which is not supported by the relevant plugins we use. This PR updates the range such that it only allows v4.X.X of fastify to be installed
> fix: prevent fastify v5 from being installed

- src/lib/timing-safe-equal.js
[`crypto.timingSafeEqual`][0] has some subtle behavior (highlighted in bold red in the docs!) when passing a `Float32Array` or `Float64Array`.  Rather than adapt our wrapper to support this unusual situation, this updates the types to avoid it.
We never took advantage of this unusual case, and now we are even less likely to.
I plan to yolo-merge this if CI passes.
[0]: https://nodejs.org/api/crypto.html#cryptotimingsafeequala-b
> chore: use more restrictive types for `timingSafeEqual`

- .github/workflows/lockfile.yml
This fixes the updating of comments by the lockfile-changes workflow. It requires a patch to the action, so we are now using our fork: https://github.com/digidem/npm-lockfile-changes/pull/1
A small thing, but it's been frustrating me getting all comments on the PR from this bot. The issue was happening because we are using a custom github app token to run the action.
> fix: fix updating comments in lockfile-changes workflow

- src/mapeo-manager.js
- test-e2e/device-info.js
We added support for this device type in 98d9981dda7aeb1bd724d7b051934db3307565a1. This lets us set it.
I think this is a useful change on its own, but it will make multiple upcoming changes easier.
*I plan to YOLO-merge this* because Gregor and I have already done this work on the `server` branch together, and this just splits it out (and fixes a type error).
> feat: set own device info to "self-hosted server"

- src/mapeo-project.js
- src/member-api.js
- test-e2e/members.js
We added support for self-hosted servers in 98d9981dda7aeb1bd724d7b051934db3307565a1. This saves the details to project-level member info.
This is a follow-up to 191369434887cc5b9908345b2c418e4a1f93325e.
_I plan to YOLO-merge this_ because Gregor and I have already done this work on the `server` branch together, and this just splits it out.
> feat: save self-hosted server details on member info

- src/mapeo-manager.js
- src/mapeo-project.js
- test-e2e/device-info.js
- test-e2e/local-peers.js
- test-e2e/sync-fuzz.js
- test-e2e/sync.js
- test-e2e/utils.js
_I recommend [reviewing this with whitespace changes disabled](https://github.com/digidem/comapeo-core/pull/856/files?w=1)._
Our tests currently connect `MapeoManager`s in two ways:
1. By starting peer discovery servers and connecting. This is similar to what the real app does.
2. By manually creating streams and connecting them in tests. This is less realistic.
This commit removes the second way because:
- it is less realistic
- it lets us remove some test-only code in the `src/` directory
- it will make an upcoming change easier
- it *used* to be significantly faster, but that's no longer true
I also tried to fix a possible (test-only) race condition, which *could* have been a reason for the less realistic option:
1. Start connecting peers by calling `connectPeers()`. This begins the …
> test: always connect peers more realistically

- proto/extensions.proto
- src/core-manager/index.js
- src/generated/extensions.d.ts
- src/generated/extensions.js
- src/generated/extensions.ts
- src/mapeo-project.js
- src/sync/sync-api.js
- src/types.ts
> chore: Send download intent to peers

- src/blob-store/downloader.js
- src/blob-store/utils.js
- test/blob-store/utils.js
To be merged into #940.
Before this change, we turned filters into a list of path prefixes and then checked entry paths against those prefixes. Rough pseudocode:
```javascript
function doesEntryMatchFilter({ path }, filter) {
const pathPrefixes = pathPrefixesFromFilter(filter)
return pathPrefixes.some((prefix) => path.startsWith(prefix))
}
```
For performance and simplicity, I think it's cleaner if we "look up" entry paths in the existing filter object. Rough pseudocode:
```javascript
function doesEntryMatchFilter({ path }, filter) {
const { type, variant } = parsePath(path)
return filter[type]?.includes(variant)
}
```
I think this has two advantages:
- It's less code. We don't need to worry about de-duping paths (e.g., `/photos/original` versus `/photos/`). We don't need to worry about …
> Invert "does this entry match the filter" logic

- types/hyperbee.d.ts
> Use `unknown` instead of `any` in Hyperbee types

- package-lock.json
- package.json
- src/constants.js
- src/datastore/README.md
- src/datastore/index.js
- src/lib/drizzle-helpers.js
- src/mapeo-manager.js
- src/mapeo-project.js
- test-e2e/migration.js
- test/data-type.js
- test/datastore.js
- test/fixtures/schema/1/0000_tearful_lake.sql
- test/fixtures/schema/1/meta/0000_snapshot.json
- test/fixtures/schema/1/meta/_journal.json
- test/fixtures/schema/1/schema.js
- test/fixtures/schema/2/0000_tearful_lake.sql
- test/fixtures/schema/2/0001_cold_wendigo.sql
- test/fixtures/schema/2/meta/0000_snapshot.json
- test/fixtures/schema/2/meta/0001_snapshot.json
- test/fixtures/schema/2/meta/_journal.json
- test/fixtures/schema/2/schema.js
- test/icon-api.js
- test/lib/drizzle-helpers.js
- test/translation-api.js
> feat: rebuild SQLite when migrations occur

- src/datastore/index.js
We have a set of promises waiting to be indexed, and we never removed these promises from the set. This fixes that memory leak.
> fix: memory leak in `DataStore`

- src/member-api.js
- test-e2e/server.js
This turns the server's `TOO_MANY_PROJECTS` error into the `SERVER_HAS_TOO_MANY_PROJECTS` error, and the `PROJECT_NOT_IN_ALLOWLIST` error into `PROJECT_NOT_IN_SERVER_ALLOWLIST` error.
See <https://github.com/digidem/comapeo-cloud/pull/33>, which adds these codes.
> feat: handle some cloud server error codes

- src/blob-store/downloader.js
This is a types-only change. We were already importing the `BlobFilter` type above, so let's use it!
> chore: use imported type in `Downloader` constructor

- src/roles.js
This change should have no impact on functionality, and is a minor change.
In [an upcoming change][0], I plan to make several references to the blocked role. This defines the `BLOCKED_ROLE` constant for this purpose.
[0]: https://github.com/digidem/comapeo-core/issues/188
> chore: define `BLOCKED_ROLE` as a constant

- test/data-type.js
This method wasn't tested...now it is!
> test: `DataType.prototype.getByVersionId`

- src/roles.js
- test-e2e/members.js
(This diff looks large, but it's just one line of source code and a bunch of tests.)
We have some code like this:
```javascript
if (isAssigningProjectCreatorRole && !this.#isProjectCreator()) {
```
The intent: only allow the project creator to change their own role.
However, `this.#isProjectCreator` returned a `Promise`, which meant that the second part of the condition *always* evaluated to `false`, which meant that the whole condition always evaluated to false, which meant that non-creators could change the creator's role.
This fixes that by making `#isProjectCreator` return a `boolean`, not `Promise<boolean>`.
Found this while working on #188.
> fix: only the project creator can change their role

- test-e2e/sync.js
In #872, we observed a bug where we seemingly had the wrong number of remote sync states. This adds a test assertion that we have the right number.
> test: assert correct number of connected devices

- src/core-ownership.js
- src/datastore/index.js
- src/errors.js
- src/mapeo-manager.js
- src/mapeo-project.js
- test/errors.js
This makes the following kind of change in a bunch of places:
```diff
-throw new Error('Not found')
+throw new NotFoundError()
```
I think this is a useful improvement on its own, but the changes to DataStore will also make [an upcoming change easier][0].
[0]: https://github.com/digidem/comapeo-core/issues/188
> chore: use `NotFoundError` utility in more places

- src/core-ownership.js
This change should have no user impact.
This directive wasn't doing anything, so we can remove it.
I plan to YOLO-merge this change.
> chore: remove unnecessary `prettier-ignore` directive

- src/blob-store/downloader.js
- src/blob-store/entries-stream.js
- src/blob-store/hyperdrive-index.js
- src/blob-store/index.js
- src/discovery/local-discovery.js
- src/fastify-plugins/maps.js
- src/lib/error.js
- src/mapeo-project.js
- src/sync/core-sync-state.js
- src/sync/namespace-sync-state.js
- src/sync/sync-api.js
- src/sync/sync-state.js
- test-e2e/sync.js
- test/lib/error.js
- test/sync/core-sync-state.js
*I recommend [reviewing this PR one commit at a time](https://github.com/digidem/comapeo-core/pull/956/commits).*
When you receive a blob filter from another peer, this updates their sync states. For example, if you receive a blob filter that says "I only want photo thumbnails", that peer's "wants" bitfield will be reduced.
Closes #682 and #905.
> feat: handle incoming blob filters

- package-lock.json
- package.json
- src/mapeo-manager.js
This updates `type-fest` to the latest version, 4.30.0. A small change was required in `src/mapeo-manager.js` to fix a TypeScript error, but this should have no impact on functionality.
> chore: update type-fest to latest version

- package-lock.json
- package.json
This is necessary for <https://github.com/digidem/comapeo-cloud/pull/36>.
> chore: update `@comapeo/schema` to 1.3.0

- package-lock.json
Update holepunch native dependencies to the latest semver compatible versions. None of these are direct dependencies, this only changes package-lock.json. Updating them ensures that we are running tests with the same native dependencies that might be used by the consumer of this module. (it doesn't guarantee it however - we need to shrinkwrap this module to guarantee  that).
> chore: update native deps

- drizzle/project/0002_new_molly_hayes.sql
- drizzle/project/meta/0002_snapshot.json
- drizzle/project/meta/_journal.json
- package-lock.json
- package.json
- test-e2e/cross-version-sync.js
- test-e2e/ipc-basic.js
- test-e2e/utils.js
This new version adds a new property to the Observation table, `migrationMetadata`. See <https://github.com/digidem/comapeo-schema/pull/280> for details.
> chore: update `@comapeo/schema` to latest version, 1.4.0

- .github/workflows/docs.yml
The docs workflow is currently broken due to our version of `upload-pages-artifact` that uses a deprecated version of the `upload-artifact` action. Updating this action requires us to use a new version of the `deploy-pages` action as well.
Used https://github.com/suzuki-shunsuke/pinact to update the relevant actions to the exact SHA hashes as opposed to using git tags, which has better security implications. Happy to update the other actions in this workflow to do the same if desired.
> chore(ci): update docs workflow to fix deprecation error

- proto/rpc.proto
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- src/local-peers.js
- src/mapeo-manager.js
- src/member-api.js
- test-e2e/manager-invite.js
- test/local-peers.js
- Added RPC acknowledge messages alongside the other RPC types
- It only enables if the other side says they have the "Ack" feature.
- This is facilitated by a new "features" flag in DeviceInfo which has a set of features we can add / remove over time. This is how we can facilitate protocol evolution over time
- This has been in service of knowing that invite actions and project details were actually seen on the other side
- We now only add a new member's role to a project after we know they got the project invite details. Fixes #1009
- Found some race conditions in the tests!
> Feat: RPC acknowledgements, add role after project details are sent

- drizzle/client/0002_brief_demogoblin.sql
- drizzle/client/meta/0002_snapshot.json
- drizzle/client/meta/_journal.json
- package-lock.json
- package.json
- proto/rpc.proto
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- src/invite/invite-api.js
- src/mapeo-manager.js
- src/member-api.js
- src/schema/client.js
- test-e2e/manager-basic.js
- test-e2e/manager-invite.js
- test-e2e/members.js
- test-e2e/project-settings.js
- test/invite-api.js
Closes #1014 
Surface area feels kind of large at the moment - I'm open to breaking it up if it makes sense to (with some guidance).
Summary of changes:
- Adds a database migration for the client database schema to add support for the `projectColor` and `projectDescription` fields as part of the `projectInfo` column.
- Updates the invite RPC message to add `projectColor` and `projectDescription` fields (both optional).
- ~**Question**: should the `projectColor` be a required field? `projectName` is a required field but not sure if the color should follow suite. Based on UX needs, maybe it makes sense to, but can also imagine it being okay to omit and letting the app handle using a fallback.~ EDIT: at the RPC level, it has to be optional for compat reasons. at the app api level, we decided …
> feat: update @comapeo/schema to 1.5.0 to introduce updated project settings schema

- src/mapeo-project.js
- src/member-api.js
- src/sync/sync-api.js
- test-e2e/server.js
Closes #999
Some specific stuff I'd like feedback on:
1. Right now this only allows removing while we're replicating. Should I initialize a replication stream if one doesn't exist instead of erroring?
2. Is removing the server by the base URL the easiest for the front end? Should we use the deviceId or some other identifier instead?
3. Are there any events we should be adding to let the front end know the server is removed, or is the role update for the server peer enough?
4. Any other tests I should include here?
> feat: remove server peer

- src/mapeo-manager.js
- src/mapeo-project.js
- src/member-api.js
- src/sync/sync-api.js
- test-e2e/server.js
Fix #1019 
We needed to catch the return of the pipeline promise.
Added ability to mock websocket connections througout the stack. As a future TODO we'll likely want to be able to mock `fetch` wherever it exists.
> fix: Catch errors connecting to server peers

- package-lock.json
- package.json
- src/fastify-plugins/maps.js
Unblocks https://github.com/digidem/comapeo-mobile/pull/1118. The only notable breaking change that this includes is the trivial rename of an export.
The lockfile changes are a bit scary looking, but think that's mostly because: 1) lots of deps changes in styled-map-package and 2) we have multiple versions of styled-map-package installed now (due to the co-existing older version of core that's installed for compat testing).
> chore: update styled-map-package to 3.0.0

- package-lock.json
- package.json
- test-e2e/cross-version-sync.js
For some reason this doesn't cause a db migration. It might be due to the new field being a deeply nested optional subfield.
Is it okay to just bump the dep without a migration here? Or should we somehow force it?
> chore: Bump @comapeo/schema dep

- src/member-api.js
This should fix https://github.com/digidem/comapeo-core/issues/1034
The issue was we weren't catching the socket closing right as replication finishes.
> fix: catch race condition in server remove

- src/index-writer/index.js
- src/sync/peer-sync-controller.js
Logging these events produces a lot of output, which has a performance overhead. We need debug logging for debugging other issues, and currently we don't have a way to set log levels to selectively log this, so turning this off for now until we can filter logs by level.
> fix: turn off debug logging for indexing and sync

- src/index.js
These are the types currently used by
dependencies, and are currently imported from
source files, which is liable to break if we
refactor code. Dependencies should be updated to
use these exports from the main entry point.
> chore: add explicit type exports

- .github/workflows/release.yml
Missed one of the steps documented in the action's [docs](https://optic.nearform.com/docs/github-action/publish-modes#oidc-trusted-publishing) that's required for using OIDC for publishing.
> chore: fix auth issue for release workflow
