digidem/comapeo-core

- lib/discovery/index.js
- lib/types.js
- types/modules.d.ts
Towards #14 
Required some code changes that I'm not entirely sure about (although existing tests pass).
> chore: add types for hyperswarm

- types/modules.d.ts
> chore: add types for random-access-file

- types/corestore.d.ts
- types/hypercore.d.ts
- types/modules.d.ts
Copied hypercore types from https://github.com/digidem/multi-core-indexer/blob/main/types/hypercore.d.ts and created types for corestore
(had a long train journey over the holidays so spent it writing some types :))
> chore: Add types for hyercore & corestore

- drizzle/client/0000_cloudy_puppet_master.sql
- drizzle/client/meta/0000_snapshot.json
- drizzle/client/meta/_journal.json
- package.json
> chore: add npm script to generate mapeo client sqlite tables

- src/datastore/README.md
- src/datastore/index.js
- src/mapeo-project.js
- tests/datastore.js
Closes #179 
Meta question: is this a (breaking?) `feat` or `chore` task??
> chore: replace Datastore IndexWriter opt with batch opt

- drizzle/client/0000_previous_nebula.sql
- drizzle/client/meta/0000_snapshot.json
- drizzle/client/meta/_journal.json
- src/schema/client.js
> chore: consolidate encryption key columns in projectKeys table

- proto/keys.proto
- proto/rpc.proto
- src/generated/keys.d.ts
- src/generated/keys.js
- src/generated/keys.ts
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- required by https://github.com/digidem/mapeo-core-next/pull/199
> feat: Add encode/decode for project keys [3/3]

- proto/rpc.proto
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
- src/rpc/index.js
- tests/rpc.js
> fix: invite.encryptionKeys should be required

- benchmarks/core-replication-state.js
- package-lock.json
- package.json
- src/core-manager/core-replication-state.js
- src/core-manager/remote-bitfield.js
- tests/core-replication-state.js
Add a new CoreReplicationState implementation, see
https://github.com/digidem/mapeo-core-next/issues/287
> feat: CoreReplicationState

- package-lock.json
- src/core-manager/index.js
- src/discovery/dns-sd.js
- src/discovery/local-discovery.js
- src/index-writer/index.js
- src/local-peers.js
- src/logger.js
- src/mapeo-manager.js
- src/mapeo-project.js
- src/sync/peer-sync-controller.js
- src/sync/sync-api.js
Extracted from #362, to ease PR review
> chore: Add debug logging

- src/icon-api.js
- tests/icon-api.js
the original intention was to use this in tests related to the fastify plugin, but didn't actually end up doing so. still something worth isolating and testing though
> chore: extract and test construction of icon url

- src/member-api.js
- test-e2e/manager-invite.js
This code was hard to follow. @gmaclennan refactored it to be clearer, and I made a few small changes to make it work.
> chore: simplify member invite code

- src/types.ts
*This is a types-only change.*
We had a bunch of unused types in `src/types.ts`. This removes them.
> chore: remove unused types

- src/translation-api.js
- test-e2e/translation-api.js
_I recommend [reviewing this with whitespace changes disabled](https://github.com/digidem/mapeo-core-next/pull/589/files?w=1)._
To be merged into #515.
> chore: add "ready" promise to translation API

- src/datatype/index.js
- src/errors.js
- src/translation-api.js
- test-e2e/translation-api.js
- tests/data-type.js
> chore: use `instanceof`, not message, for "not found" error

- tests/sync/core-sync-state.js
This test-only change fixes a few type errors in this file.
> chore: fix various type errors in core sync state tests

- tests/blob-store/blob-store.js
> chore: fix type errors in blob store tests

- tests/blob-store/live-download.js
- types/hyperdrive.d.ts
This is a test-only change that should have no impact on functionality.
> chore: fix type errors in blob store live download tests

- src/local-peers.js
- src/sync/peer-sync-controller.js
> chore: replace ts-ignore with types for logging functions

- src/core-manager/index.js
See [the comments on this commit][0].
[0]: https://github.com/digidem/mapeo-core-next/commit/6ad3beaaff8d10d4a23a52380e73d8f76c833928
> chore: catch failures to send pre-have messages

- test-e2e/utils.js
_This is a test-only change. It is not urgent._
This fixes two small issues with the createManager test utility:
- Removes a `@ts-ignore` directive
- Avoid an unnecessary `t.teardown` call
These changes should have no impact.
(For some reason, I have wanted to tidy this every time I've looked at it...this
is me being nitpicky to the max.)
> chore: clean up test createManager utility

- tests/discovery/local-discovery.js
This test-only change drops Brittle from our LocalDiscovery tests and
replaces them with `node:test` and `node:assert`.
> test: move LocalDiscovery tests to `node:test`

- tests/invite-api.js
This test-only change drops Brittle from our invite API tests and replaces them with `node:test` and `node:assert`.
> test: move invite API tests to `node:test`

- package-lock.json
- package.json
This is a simple patch version upgrade.
> chore: update `mime` to latest version

- tests/local-peers.js
This test-only change drops Brittle from our LocalPeers tests and replaces them with `node:test` and `node:assert`.
> test: move LocalPeers tests to `node:test`

- .github/workflows/release.yml
This reverts commit 96692651bb82887f14c7e47694d5873c7164317f.
> ci: run release workflow on PR close to fix releases

- src/mapeo-project.js
- test-e2e/project-leave.js
Closes #717, which has more background on the motivation for this change.
> feat: you can now leave a project if you're the only member

- package-lock.json
- package.json
- proto/rpc.proto
- src/generated/rpc.d.ts
- src/generated/rpc.js
- src/generated/rpc.ts
Additionally, I've added `deviceType.selfHostedServer` on proto/rpc.proto since it was introduced on last schema definition
> chore: update mapeo/schema

- package-lock.json
- package.json
updates schema with fix to ESM code
> chore: update mapeo-schema & mapeo-mock-data

- src/sync/namespace-sync-state.js
@tomasciccola and I noticed what may be a potential typo that was introduced in #793. Not really sure so putting this up for anyone with more context to weigh in.
Here the's diff from that PR for this file:
https://github.com/digidem/comapeo-core/commit/304eb6066030c55a1372e48a2ae06db4d1ec879a#diff-db61454aa8ac68ad0a3bd838ddb40e0a2d23b6d9702f8813e4292566e9871e0aR187
> fix: fix check in mutatingAddPeerState

- package-lock.json
- package.json
_This change is not urgent._
This test-only dependency was a little out of date.
> test: update `bitfield` dependency

- test-e2e/utils.js
`connectPeers` returns a function. That function returns a `Promise`, not `void`. I'm not sure why this type-checked, but this fixes it by making it return a `Promise<void>`.
> test: clean up return type for `connectPeers`

- package-lock.json
- package.json
- src/server/comapeo-plugin.js
- src/server/server.js
Add `server.js` script to start server. Should be run with `node ./server`.
Depends on several environment variables, see script for descriptions.
> feat: add server.js script

- src/member-api.js
- src/server/routes.js
- src/server/test/add-project-endpoint.js
- src/server/test/list-projects-endpoint.js
- src/server/test/observations-endpoint.js
- src/server/test/sync-endpoint.js
- test-e2e/server.js
Closes <https://github.com/digidem/comapeo-cloud/issues/19>.
I plan to yolo-merge this change into the `server` branch.
> Server: PUT /projects, not POST /projects

- src/fastify-plugins/maps.js
- src/fastify-plugins/utils.js
- test/fastify-plugins/maps.js
> fix(maps): enable CORS for style json response

- src/mapeo-project.js
> fix: proper date and media folder for exports

- src/invite/invite-state-machine.js
- src/mapeo-manager.js
> Increase all invite timeouts

- src/invite/invite-state-machine.js
- src/mapeo-manager.js
> fix: Change project add timeouts

- src/mapeo-manager.js
- test-e2e/manager-archive-device.js
needed for https://github.com/digidem/comapeo-mobile/issues/956
More straightforward than inferring from device type IMO
> feat: Add setting for default archive device value
